### ISSUE TITLE
Replace PkRequestManager

### ISSUE THREAD

**Issue by plusCubed** [afollestad/polar-dashboard#10]
Probably by creating a custom implementation since that has... problems

**Comment by afollestad** [comment]
I believe @PDDStudio has a solution that could solve this

**Comment by PDDStudio** [comment]
I've already created something similar to what you're looking for. As discussed with @afollestad already, we're going to extend it and adjust it to work perfectly with polar.
We should discuss this in the next few days to get a list of feature

**Comment by afollestad** [comment]
I think this should be a relatively high priority change since some people complain about its performance

**Comment by plusCubed** [comment]
I was going to roll this into #15 for using Firebase since the sending would be pretty different (it would not use a zip to send an email, but rather directly modify the database).

**Comment by afollestad** [comment]
I'm actually working on a new library right now since I need to release an update for Polar in 3 hours or less from now

**Comment by plusCubed** [comment]
@afollestad Sounds good. This is more of a long-term plan thing I guess.
