### ISSUE TITLE
How to Include Searchbar ? 

### ISSUE THREAD

**Issue by uidhinc** [afollestad/polar-dashboard#100]
MLV has included the Google search bar in all his themes.And this is so awesome to go with a theme .
Can we include that in Polar too ? It would be a complete Package then 
![4-10-2016 9-34-38 am](https://cloud.githubusercontent.com/assets/18343840/14408026/b1cda658-feff-11e5-897f-413586e0fa8c.png)

![4-10-2016 9-37-08 am](https://cloud.githubusercontent.com/assets/18343840/14408029/cfcf589a-feff-11e5-98b8-49a30f313b67.png)

**Comment by afollestad** [comment]
No, you'll have to do that yourself. 

You could use Polar's Zooper integration if you want.

**Comment by uidhinc** [comment]
Ok But This is not through Zooper ...This is themeing the gogle search bar.I checked.Wish you could have helped.
