### ISSUE TITLE
Leaving app by pressing Back Button causes FC

### ISSUE THREAD

**Issue by dominick93** [afollestad/polar-dashboard#102]
Happens with my edited app as well as the default Polar Dashboard downloaded from Play Strore.

(Nexus 5, Android 6.0.1)

**Comment by ercsoftware11** [comment]
I am having the same issue!

**Comment by ercsoftware11** [comment]
Hey so I might have figured something out. I added in my own splash screen, and when the splash screen loads, I use an Uncaught exception handler that catches whatever exception is made when the app is closing. Once this occurs, I just kill the app and no error message is displayed. Obviously this is not a permanent fix, however is definitely better than what it was. 

Below is the code for my splash screen and the Uncaught exception. 

Hope this helps a little as a temporary solution

`public class SplashScreen extends Activity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        // TODO Auto-generated method stub
        super.onCreate(savedInstanceState);
        setContentView(R.layout.splash);
        Thread.setDefaultUncaughtExceptionHandler (new Thread.UncaughtExceptionHandler()
        {
            @Override
            public void uncaughtException (Thread thread, Throwable e)
            {
                handleUncaughtException (thread, e);
            }
        });

        Thread timerThread = new Thread(){
            public void run(){
                try{
                    sleep(1000);
                }catch(InterruptedException e){
                    e.printStackTrace();
                }finally{
                    Intent intent = new Intent(SplashScreen.this,MainActivity.class);
                    startActivity(intent);
                }
            }
        };
        timerThread.start();
    }

    @Override
    protected void onPause() {
        // TODO Auto-generated method stub
        super.onPause();
        finish();
    }

    public void handleUncaughtException (Thread thread, Throwable e)
    {
        e.printStackTrace(); // not all Android versions will print the stack trace automatically

        System.exit(1); // kill off the crashed app
    }
}`

**Comment by afollestad** [comment]
@dominick93 first, make sure your app is using the latest version of the dashboard.

Second, could you get me a logcat?

**Comment by afollestad** [comment]
Offically fixed, will be in the next release.

**Comment by ercsoftware11** [comment]
Thanks for the help :+1:

**Comment by dominick93** [comment]
Thank you guys :)

**Comment by ercsoftware11** [comment]
I dont think it is fixed?? I updated the source and its still crashing when closing

**Comment by dominick93** [comment]
I'll try tomorrow once I get to my PC.

**Comment by ercsoftware11** [comment]
Okay awesome. Would be great to fix. Its kind of annoying how it closes then stops working (apparently). @afollestad Polar is a great dashboard.

**Comment by dominick93** [comment]
Confirming the bug is still present. I've no idea if that's what you need but there is the logcat: https://drive.google.com/file/d/0BzzK6Nhsa6N1TTFWQ2tBOVFNcEk/view?usp=sharing

**Comment by ercsoftware11** [comment]
I have no idea how to read that :-/ But anyway do we need to open another issue?

**Comment by afollestad** [comment]
The only important part of the file is:

```Gradle
04-20 12:54:53.604: E/AndroidRuntime(11092): Process: com.kndrv.artico, PID: 11092
04-20 12:54:53.604: E/AndroidRuntime(11092): java.lang.IllegalStateException: Inquiry's context was null. Deinit() was probably run already.
04-20 12:54:53.604: E/AndroidRuntime(11092): 	at com.afollestad.inquiry.Query.run(Query.java:205)
04-20 12:54:53.604: E/AndroidRuntime(11092): 	at com.afollestad.inquiry.Query$2.run(Query.java:259)
04-20 12:54:53.604: E/AndroidRuntime(11092): 	at java.lang.Thread.run(Thread.java:818)
```

You read error logcats by looking for the word `Exception`.

---

That's what I had fixed recently, though. Are you sure you're using the latest code?

**Comment by dominick93** [comment]
I'm sure buddy, I've also tried the clean Polar template without customization and the same result...Since the new update I've also experienced a problem that the Dashboard app takes long to launch...sometimes you see even 6 sec of white screen

**Comment by TWellington** [comment]
If you want to discuss cold start times, we can start another ticket. We
haven't ever seen a cold start time that long on our end. Leaving the app
by pressing the back button only causes the app to FC once you open it
again, Aidan (I'm not sure if you knew that bit or not, I don't remember
due to the amount of emails I've gotten from this thread).

**Comment by ercsoftware11** [comment]
The app crashing is caused when the app has completely closed (not visible anymore), not when you open it again. I have not had any issues with cold start times
