### ISSUE TITLE
Leaving app by pushing back button causes app to crash (message saying unfortunately polar has stopped) 

### ISSUE THREAD

**Issue by ercsoftware11** [afollestad/polar-dashboard#103]
When I push the back button to leave the app, it closes then apparently crashes. Android displays the message: Unfortunately Polar has stopped. This happens even when the package name is something different. It will still say, Unfortunately <Your Package Name> has stopped. Is anyone else having the same issue?

**Comment by afollestad** [comment]
Duplicate of an already open issue.
