### ISSUE TITLE
Crashing on KitKat - Latest Polar version. 

### ISSUE THREAD

**Issue by ryanmkelly** [afollestad/polar-dashboard#104]
Hey, I've been receiving a bunch crashes on various 4.4 devices since updating to the latest Polar version. 

http://pastebin.com/ZngEm1QA

**Comment by afollestad** [comment]
Are you sure you have the latest version? I just tried to latest version on a 4.4 device and don't have any issues.

**Comment by ryanmkelly** [comment]
I used the upgrade tool on Thursday or Friday.

**Comment by afollestad** [comment]
Are the crashes from other users? Maybe they don't have the latest version of your pack.

**Comment by ryanmkelly** [comment]
They do, had one contact me saying it only started after the update

**Comment by afollestad** [comment]
Well I probably won't be able to do much about it right now unless I'm able to reproduce it.

**Comment by afollestad** [comment]
c

**Comment by afollestad** [comment]
Pushed more code to help
