### ISSUE TITLE
Support for Xperia Launcher?

### ISSUE THREAD

**Issue by ryanmkelly** [afollestad/polar-dashboard#105]
Sony have added support to the Xperia Launcher and I've been getting requests if it's possible to add it in. 

I think it's possible to bundle it, this one works with Xperia and Nova: https://play.google.com/store/apps/details?id=com.whicons.iconpack

**Comment by TWellington** [comment]
I'm not finding anything on how to support Xperia home online, and I'm not totally sure where to look. That icon pack is also using IconShowcase, so maybe that's something included there.

**Comment by afollestad** [comment]
I've added the intent filter, but I'm not sure if there's any intent used to apply from the dashboard.
