### ISSUE TITLE
Add support for Kustom (KWGT, KLWP)

### ISSUE THREAD

**Issue by frmz** [afollestad/polar-dashboard#106]
Kustom is a theming engine very much like Zooper but with constant updates, a [LOT more features](https://kustom.uservoice.com/knowledgebase/articles/753159-how-kwgt-compares-with-zooper-buzz-uccw) and supports the distribution of both [live wallpapers](https://play.google.com/store/apps/details?id=org.kustom.wallpaper), [widgets](https://play.google.com/store/apps/details?id=org.kustom.widget) and "[komponents](https://play.google.com/store/search?q=komponent&c=apps&docType=1)" which are very much like lightweight reusable modules inside the engine.

It works very much like Zooper in terms of distribution of the skins BUT its also capable of distributing weather packs natively (as komponents), an example of the manifest and the content provider is available [here](https://bitbucket.org/frankmonza/kustomskinsample)

I am the author, so if you are ok I can fork and provide a pull request to add support for it, any guidelines on what to edit add? Would you consider accepting a pull request?

**Comment by afollestad** [comment]
https://github.com/afollestad/polar-dashboard/pull/138
