### ISSUE TITLE
App drawer icon on ZenUI Launcher

### ISSUE THREAD

**Issue by VictorRodriguezVR** [afollestad/polar-dashboard#108]
I have seen some themes have themed the app drawer icon on ZenUi Launcher. I hope it is possible to add it to Polar. 

Thanks ;)

**Comment by TWellington** [comment]
We don't have any documentation on how to do that.

**Comment by VictorRodriguezVR** [comment]
I understand. I have seen the themes using IconShowcase have the app drawer
icon themed on ZenUI. Maybe it's possible add from it.

**Comment by TWellington** [comment]
It's probably not something to do with Polar or IconShowcase, but, rather,
something to do with the naming of your icon. Have you looked into it for
yourself?

**Comment by djv-shyfoundry** [comment]
To get the app drawer to display on the ZenUI Launcher create a new drawable xml named all_apps_button_icon.xml: 

<?xml version="1.0" encoding="utf-8"?>
<selector
  xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:state_focused="true" android:drawable="@drawable/YOUR_DRAWABLE" />
    <item android:state_pressed="true" android:drawable="@drawable/YOUR_DRAWABLE" />
    <item android:drawable="@drawable/YOUR_DRAWABLE" />
</selector>

**Comment by TWellington** [comment]
Thank you, @djv-shyfoundry!
