### ISSUE TITLE
IconRequest FC on exit

### ISSUE THREAD

**Issue by zdunex25** [afollestad/polar-dashboard#109]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Polar Dashboard.
- [x] I have given my issue a non-generic title.

###### Include the following:
 - Polar Dashboard version: `latest`
 - Device OS version: `6.0.1`
 - Device Manufacturer: `Xiaomi`
 - Device Name: `MI4W`

```java
E/AndroidRuntime: FATAL EXCEPTION: Thread-1563
    Process: com.afollestad.polar, PID: 24986
    java.lang.NullPointerException
        at com.afollestad.iconrequest.IconRequest$4.run(IconRequest.java:343)
        at java.lang.Thread.run(Thread.java:841)
```
 
###### Reproduction Steps

1. Start dashboard and press back you will get this FC, stragne thing is if you switch to any tab (like walls, icons, about) and then exit there is no FC.

**Comment by zdunex25** [comment]
Differend kind of FC after 65c228a
```java
E/AndroidRuntime: FATAL EXCEPTION: Thread-17063
    Process: com.afollestad.polar, PID: 10235
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Handler.post(java.lang.Runnable)' on a null object reference
        at com.afollestad.iconrequest.IconRequest$4.run(IconRequest.java:335)
        at java.lang.Thread.run(Thread.java:818)
```

**Comment by afollestad** [comment]
The latest code should resolve the problem, I hope
