### ISSUE TITLE
Go Launcher problems?

### ISSUE THREAD

**Issue by VictorRodriguezVR** [afollestad/polar-dashboard#113]
I've been testing in some launchers the compatibility of my themes and I've had some problems.

In Go Launcher and Atom Launcher the icons do not apply.

Thanks

**Comment by afollestad** [comment]
For Atom Launcher: https://github.com/afollestad/polar-dashboard/issues/96

**Comment by afollestad** [comment]
Any quick apply additions will require new graphics from @TWellington

**Comment by VictorRodriguezVR** [comment]
Sorry I tried again the Quick Apply for Smart launcher and its worked

**Comment by afollestad** [comment]
Others have reported there are no problems with GO Launcher
