### ISSUE TITLE
Android Studio Export Problem?

### ISSUE THREAD

**Issue by Kexagia** [afollestad/polar-dashboard#115]
Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not find com.android.support:appcompat-v7:23.4.0.
     Searched in the following locations:
         file:/C:/Program Files/Android/Android Studio/gradle/m2repository/com/android/support/appcompat-v7/23.4.0/appcompat-v7-23.4.0.pom
         file:/C:/Program Files/Android/Android Studio/gradle/m2repository/com/android/support/appcompat-v7/23.4.0/appcompat-v7-23.4.0.jar
         https://jcenter.bintray.com/com/android/support/appcompat-v7/23.4.0/appcompat-v7-23.4.0.pom
         https://jcenter.bintray.com/com/android/support/appcompat-v7/23.4.0/appcompat-v7-23.4.0.jar
         https://jitpack.io/com/android/support/appcompat-v7/23.4.0/appcompat-v7-23.4.0.pom
         https://jitpack.io/com/android/support/appcompat-v7/23.4.0/appcompat-v7-23.4.0.jar
         https://repo1.maven.org/maven2/com/android/support/appcompat-v7/23.4.0/appcompat-v7-23.4.0.pom
         https://repo1.maven.org/maven2/com/android/support/appcompat-v7/23.4.0/appcompat-v7-23.4.0.jar
         https://dl.bintray.com/drummer-aidan/maven/com/android/support/appcompat-v7/23.4.0/appcompat-v7-23.4.0.pom
         https://dl.bintray.com/drummer-aidan/maven/com/android/support/appcompat-v7/23.4.0/appcompat-v7-23.4.0.jar
         file:/C:/Users/Home/AppData/Local/Android/sdk/extras/android/m2repository/com/android/support/appcompat-v7/23.4.0/appcompat-v7-23.4.0.pom
         file:/C:/Users/Home/AppData/Local/Android/sdk/extras/android/m2repository/com/android/support/appcompat-v7/23.4.0/appcompat-v7-23.4.0.jar
         file:/C:/Users/Home/AppData/Local/Android/sdk/extras/google/m2repository/com/android/support/appcompat-v7/23.4.0/appcompat-v7-23.4.0.pom
         file:/C:/Users/Home/AppData/Local/Android/sdk/extras/google/m2repository/com/android/support/appcompat-v7/23.4.0/appcompat-v7-23.4.0.jar
     Required by:
         polar-dashboard-master:app:unspecified
         polar-dashboard-master:app:unspecified > com.afollestad.material-dialogs:core:0.8.5.9
   > Could not find com.android.support:recyclerview-v7:23.4.0.
     Searched in the following locations:
         file:/C:/Program Files/Android/Android Studio/gradle/m2repository/com/android/support/recyclerview-v7/23.4.0/recyclerview-v7-23.4.0.pom
         file:/C:/Program Files/Android/Android Studio/gradle/m2repository/com/android/support/recyclerview-v7/23.4.0/recyclerview-v7-23.4.0.jar
         https://jcenter.bintray.com/com/android/support/recyclerview-v7/23.4.0/recyclerview-v7-23.4.0.pom
         https://jcenter.bintray.com/com/android/support/recyclerview-v7/23.4.0/recyclerview-v7-23.4.0.jar
         https://jitpack.io/com/android/support/recyclerview-v7/23.4.0/recyclerview-v7-23.4.0.pom
         https://jitpack.io/com/android/support/recyclerview-v7/23.4.0/recyclerview-v7-23.4.0.jar
         https://repo1.maven.org/maven2/com/android/support/recyclerview-v7/23.4.0/recyclerview-v7-23.4.0.pom
         https://repo1.maven.org/maven2/com/android/support/recyclerview-v7/23.4.0/recyclerview-v7-23.4.0.jar
         https://dl.bintray.com/drummer-aidan/maven/com/android/support/recyclerview-v7/23.4.0/recyclerview-v7-23.4.0.pom
         https://dl.bintray.com/drummer-aidan/maven/com/android/support/recyclerview-v7/23.4.0/recyclerview-v7-23.4.0.jar
         file:/C:/Users/Home/AppData/Local/Android/sdk/extras/android/m2repository/com/android/support/recyclerview-v7/23.4.0/recyclerview-v7-23.4.0.pom
         file:/C:/Users/Home/AppData/Local/Android/sdk/extras/android/m2repository/com/android/support/recyclerview-v7/23.4.0/recyclerview-v7-23.4.0.jar
         file:/C:/Users/Home/AppData/Local/Android/sdk/extras/google/m2repository/com/android/support/recyclerview-v7/23.4.0/recyclerview-v7-23.4.0.pom
         file:/C:/Users/Home/AppData/Local/Android/sdk/extras/google/m2repository/com/android/support/recyclerview-v7/23.4.0/recyclerview-v7-23.4.0.jar
     Required by:
         polar-dashboard-master:app:unspecified
         polar-dashboard-master:app:unspecified > com.afollestad.material-dialogs:core:0.8.5.9
   > Could not find com.android.support:support-v13:23.4.0.
     Searched in the following locations:
         file:/C:/Program Files/Android/Android Studio/gradle/m2repository/com/android/support/support-v13/23.4.0/support-v13-23.4.0.pom
         file:/C:/Program Files/Android/Android Studio/gradle/m2repository/com/android/support/support-v13/23.4.0/support-v13-23.4.0.jar
         https://jcenter.bintray.com/com/android/support/support-v13/23.4.0/support-v13-23.4.0.pom
         https://jcenter.bintray.com/com/android/support/support-v13/23.4.0/support-v13-23.4.0.jar
         https://jitpack.io/com/android/support/support-v13/23.4.0/support-v13-23.4.0.pom
         https://jitpack.io/com/android/support/support-v13/23.4.0/support-v13-23.4.0.jar
         https://repo1.maven.org/maven2/com/android/support/support-v13/23.4.0/support-v13-23.4.0.pom
         https://repo1.maven.org/maven2/com/android/support/support-v13/23.4.0/support-v13-23.4.0.jar
         https://dl.bintray.com/drummer-aidan/maven/com/android/support/support-v13/23.4.0/support-v13-23.4.0.pom
         https://dl.bintray.com/drummer-aidan/maven/com/android/support/support-v13/23.4.0/support-v13-23.4.0.jar
         file:/C:/Users/Home/AppData/Local/Android/sdk/extras/android/m2repository/com/android/support/support-v13/23.4.0/support-v13-23.4.0.pom
         file:/C:/Users/Home/AppData/Local/Android/sdk/extras/android/m2repository/com/android/support/support-v13/23.4.0/support-v13-23.4.0.jar
         file:/C:/Users/Home/AppData/Local/Android/sdk/extras/google/m2repository/com/android/support/support-v13/23.4.0/support-v13-23.4.0.pom
         file:/C:/Users/Home/AppData/Local/Android/sdk/extras/google/m2repository/com/android/support/support-v13/23.4.0/support-v13-23.4.0.jar
     Required by:
         polar-dashboard-master:app:unspecified
   > Could not find com.android.support:design:23.4.0.
     Searched in the following locations:
         file:/C:/Program Files/Android/Android Studio/gradle/m2repository/com/android/support/design/23.4.0/design-23.4.0.pom
         file:/C:/Program Files/Android/Android Studio/gradle/m2repository/com/android/support/design/23.4.0/design-23.4.0.jar
         https://jcenter.bintray.com/com/android/support/design/23.4.0/design-23.4.0.pom
         https://jcenter.bintray.com/com/android/support/design/23.4.0/design-23.4.0.jar
         https://jitpack.io/com/android/support/design/23.4.0/design-23.4.0.pom
         https://jitpack.io/com/android/support/design/23.4.0/design-23.4.0.jar
         https://repo1.maven.org/maven2/com/android/support/design/23.4.0/design-23.4.0.pom
         https://repo1.maven.org/maven2/com/android/support/design/23.4.0/design-23.4.0.jar
         https://dl.bintray.com/drummer-aidan/maven/com/android/support/design/23.4.0/design-23.4.0.pom
         https://dl.bintray.com/drummer-aidan/maven/com/android/support/design/23.4.0/design-23.4.0.jar
         file:/C:/Users/Home/AppData/Local/Android/sdk/extras/android/m2repository/com/android/support/design/23.4.0/design-23.4.0.pom
         file:/C:/Users/Home/AppData/Local/Android/sdk/extras/android/m2repository/com/android/support/design/23.4.0/design-23.4.0.jar
         file:/C:/Users/Home/AppData/Local/Android/sdk/extras/google/m2repository/com/android/support/design/23.4.0/design-23.4.0.pom
         file:/C:/Users/Home/AppData/Local/Android/sdk/extras/google/m2repository/com/android/support/design/23.4.0/design-23.4.0.jar
     Required by:
         polar-dashboard-master:app:unspecified
   > Could not find com.android.support:cardview-v7:23.4.0.
     Searched in the following locations:
         file:/C:/Program Files/Android/Android Studio/gradle/m2repository/com/android/support/cardview-v7/23.4.0/cardview-v7-23.4.0.pom
         file:/C:/Program Files/Android/Android Studio/gradle/m2repository/com/android/support/cardview-v7/23.4.0/cardview-v7-23.4.0.jar
         https://jcenter.bintray.com/com/android/support/cardview-v7/23.4.0/cardview-v7-23.4.0.pom
         https://jcenter.bintray.com/com/android/support/cardview-v7/23.4.0/cardview-v7-23.4.0.jar
         https://jitpack.io/com/android/support/cardview-v7/23.4.0/cardview-v7-23.4.0.pom
         https://jitpack.io/com/android/support/cardview-v7/23.4.0/cardview-v7-23.4.0.jar
         https://repo1.maven.org/maven2/com/android/support/cardview-v7/23.4.0/cardview-v7-23.4.0.pom
         https://repo1.maven.org/maven2/com/android/support/cardview-v7/23.4.0/cardview-v7-23.4.0.jar
         https://dl.bintray.com/drummer-aidan/maven/com/android/support/cardview-v7/23.4.0/cardview-v7-23.4.0.pom
         https://dl.bintray.com/drummer-aidan/maven/com/android/support/cardview-v7/23.4.0/cardview-v7-23.4.0.jar
         file:/C:/Users/Home/AppData/Local/Android/sdk/extras/android/m2repository/com/android/support/cardview-v7/23.4.0/cardview-v7-23.4.0.pom
         file:/C:/Users/Home/AppData/Local/Android/sdk/extras/android/m2repository/com/android/support/cardview-v7/23.4.0/cardview-v7-23.4.0.jar
         file:/C:/Users/Home/AppData/Local/Android/sdk/extras/google/m2repository/com/android/support/cardview-v7/23.4.0/cardview-v7-23.4.0.pom
         file:/C:/Users/Home/AppData/Local/Android/sdk/extras/google/m2repository/com/android/support/cardview-v7/23.4.0/cardview-v7-23.4.0.jar
     Required by:
         polar-dashboard-master:app:unspecified
   > Could not find com.android.support:palette-v7:23.4.0.
     Searched in the following locations:
         file:/C:/Program Files/Android/Android Studio/gradle/m2repository/com/android/support/palette-v7/23.4.0/palette-v7-23.4.0.pom
         file:/C:/Program Files/Android/Android Studio/gradle/m2repository/com/android/support/palette-v7/23.4.0/palette-v7-23.4.0.jar
         https://jcenter.bintray.com/com/android/support/palette-v7/23.4.0/palette-v7-23.4.0.pom
         https://jcenter.bintray.com/com/android/support/palette-v7/23.4.0/palette-v7-23.4.0.jar
         https://jitpack.io/com/android/support/palette-v7/23.4.0/palette-v7-23.4.0.pom
         https://jitpack.io/com/android/support/palette-v7/23.4.0/palette-v7-23.4.0.jar
         https://repo1.maven.org/maven2/com/android/support/palette-v7/23.4.0/palette-v7-23.4.0.pom
         https://repo1.maven.org/maven2/com/android/support/palette-v7/23.4.0/palette-v7-23.4.0.jar
         https://dl.bintray.com/drummer-aidan/maven/com/android/support/palette-v7/23.4.0/palette-v7-23.4.0.pom
         https://dl.bintray.com/drummer-aidan/maven/com/android/support/palette-v7/23.4.0/palette-v7-23.4.0.jar
         file:/C:/Users/Home/AppData/Local/Android/sdk/extras/android/m2repository/com/android/support/palette-v7/23.4.0/palette-v7-23.4.0.pom
         file:/C:/Users/Home/AppData/Local/Android/sdk/extras/android/m2repository/com/android/support/palette-v7/23.4.0/palette-v7-23.4.0.jar
         file:/C:/Users/Home/AppData/Local/Android/sdk/extras/google/m2repository/com/android/support/palette-v7/23.4.0/palette-v7-23.4.0.pom
         file:/C:/Users/Home/AppData/Local/Android/sdk/extras/google/m2repository/com/android/support/palette-v7/23.4.0/palette-v7-23.4.0.jar
     Required by:
         polar-dashboard-master:app:unspecified
   > Could not find com.android.support:support-v4:23.4.0.
     Searched in the following locations:
         file:/C:/Program Files/Android/Android Studio/gradle/m2repository/com/android/support/support-v4/23.4.0/support-v4-23.4.0.pom
         file:/C:/Program Files/Android/Android Studio/gradle/m2repository/com/android/support/support-v4/23.4.0/support-v4-23.4.0.jar
         https://jcenter.bintray.com/com/android/support/support-v4/23.4.0/support-v4-23.4.0.pom
         https://jcenter.bintray.com/com/android/support/support-v4/23.4.0/support-v4-23.4.0.jar
         https://jitpack.io/com/android/support/support-v4/23.4.0/support-v4-23.4.0.pom
         https://jitpack.io/com/android/support/support-v4/23.4.0/support-v4-23.4.0.jar
         https://repo1.maven.org/maven2/com/android/support/support-v4/23.4.0/support-v4-23.4.0.pom
         https://repo1.maven.org/maven2/com/android/support/support-v4/23.4.0/support-v4-23.4.0.jar
         https://dl.bintray.com/drummer-aidan/maven/com/android/support/support-v4/23.4.0/support-v4-23.4.0.pom
         https://dl.bintray.com/drummer-aidan/maven/com/android/support/support-v4/23.4.0/support-v4-23.4.0.jar
         file:/C:/Users/Home/AppData/Local/Android/sdk/extras/android/m2repository/com/android/support/support-v4/23.4.0/support-v4-23.4.0.pom
         file:/C:/Users/Home/AppData/Local/Android/sdk/extras/android/m2repository/com/android/support/support-v4/23.4.0/support-v4-23.4.0.jar
         file:/C:/Users/Home/AppData/Local/Android/sdk/extras/google/m2repository/com/android/support/support-v4/23.4.0/support-v4-23.4.0.pom
         file:/C:/Users/Home/AppData/Local/Android/sdk/extras/google/m2repository/com/android/support/support-v4/23.4.0/support-v4-23.4.0.jar
     Required by:
         polar-dashboard-master:app:unspecified > com.afollestad.material-dialogs:core:0.8.5.9
   > Could not find com.android.support:support-annotations:23.4.0.
     Searched in the following locations:
         file:/C:/Program Files/Android/Android Studio/gradle/m2repository/com/android/support/support-annotations/23.4.0/support-annotations-23.4.0.pom
         file:/C:/Program Files/Android/Android Studio/gradle/m2repository/com/android/support/support-annotations/23.4.0/support-annotations-23.4.0.jar
         https://jcenter.bintray.com/com/android/support/support-annotations/23.4.0/support-annotations-23.4.0.pom
         https://jcenter.bintray.com/com/android/support/support-annotations/23.4.0/support-annotations-23.4.0.jar
         https://jitpack.io/com/android/support/support-annotations/23.4.0/support-annotations-23.4.0.pom
         https://jitpack.io/com/android/support/support-annotations/23.4.0/support-annotations-23.4.0.jar
         https://repo1.maven.org/maven2/com/android/support/support-annotations/23.4.0/support-annotations-23.4.0.pom
         https://repo1.maven.org/maven2/com/android/support/support-annotations/23.4.0/support-annotations-23.4.0.jar
         https://dl.bintray.com/drummer-aidan/maven/com/android/support/support-annotations/23.4.0/support-annotations-23.4.0.pom
         https://dl.bintray.com/drummer-aidan/maven/com/android/support/support-annotations/23.4.0/support-annotations-23.4.0.jar
         file:/C:/Users/Home/AppData/Local/Android/sdk/extras/android/m2repository/com/android/support/support-annotations/23.4.0/support-annotations-23.4.0.pom
         file:/C:/Users/Home/AppData/Local/Android/sdk/extras/android/m2repository/com/android/support/support-annotations/23.4.0/support-annotations-23.4.0.jar
         file:/C:/Users/Home/AppData/Local/Android/sdk/extras/google/m2repository/com/android/support/support-annotations/23.4.0/support-annotations-23.4.0.pom
         file:/C:/Users/Home/AppData/Local/Android/sdk/extras/google/m2repository/com/android/support/support-annotations/23.4.0/support-annotations-23.4.0.jar
     Required by:
         polar-dashboard-master:app:unspecified > com.afollestad.material-dialogs:core:0.8.5.9
         polar-dashboard-master:app:unspecified > com.afollestad:icon-request:1.3.6
   > Could not find com.android.support:recyclerview-v7:23.4.0.
     Searched in the following locations:
         file:/C:/Program Files/Android/Android Studio/gradle/m2repository/com/android/support/recyclerview-v7/23.4.0/recyclerview-v7-23.4.0.pom
         file:/C:/Program Files/Android/Android Studio/gradle/m2repository/com/android/support/recyclerview-v7/23.4.0/recyclerview-v7-23.4.0.jar
         https://jcenter.bintray.com/com/android/support/recyclerview-v7/23.4.0/recyclerview-v7-23.4.0.pom
         https://jcenter.bintray.com/com/android/support/recyclerview-v7/23.4.0/recyclerview-v7-23.4.0.jar
         https://jitpack.io/com/android/support/recyclerview-v7/23.4.0/recyclerview-v7-23.4.0.pom
         https://jitpack.io/com/android/support/recyclerview-v7/23.4.0/recyclerview-v7-23.4.0.jar
         https://repo1.maven.org/maven2/com/android/support/recyclerview-v7/23.4.0/recyclerview-v7-23.4.0.pom
         https://repo1.maven.org/maven2/com/android/support/recyclerview-v7/23.4.0/recyclerview-v7-23.4.0.jar
         https://dl.bintray.com/drummer-aidan/maven/com/android/support/recyclerview-v7/23.4.0/recyclerview-v7-23.4.0.pom
         https://dl.bintray.com/drummer-aidan/maven/com/android/support/recyclerview-v7/23.4.0/recyclerview-v7-23.4.0.jar
         file:/C:/Users/Home/AppData/Local/Android/sdk/extras/android/m2repository/com/android/support/recyclerview-v7/23.4.0/recyclerview-v7-23.4.0.pom
         file:/C:/Users/Home/AppData/Local/Android/sdk/extras/android/m2repository/com/android/support/recyclerview-v7/23.4.0/recyclerview-v7-23.4.0.jar
         file:/C:/Users/Home/AppData/Local/Android/sdk/extras/google/m2repository/com/android/support/recyclerview-v7/23.4.0/recyclerview-v7-23.4.0.pom
         file:/C:/Users/Home/AppData/Local/Android/sdk/extras/google/m2repository/com/android/support/recyclerview-v7/23.4.0/recyclerview-v7-23.4.0.jar
     Required by:
         polar-dashboard-master:app:unspecified > com.afollestad:drag-select-recyclerview:0.3.5
         polar-dashboard-master:app:unspecified > com.afollestad:sectioned-recyclerview:0.2.2
   > Could not find com.android.support:support-annotations:23.4.0.
     Searched in the following locations:
         file:/C:/Program Files/Android/Android Studio/gradle/m2repository/com/android/support/support-annotations/23.4.0/support-annotations-23.4.0.pom
         file:/C:/Program Files/Android/Android Studio/gradle/m2repository/com/android/support/support-annotations/23.4.0/support-annotations-23.4.0.jar
         https://jcenter.bintray.com/com/android/support/support-annotations/23.4.0/support-annotations-23.4.0.pom
         https://jcenter.bintray.com/com/android/support/support-annotations/23.4.0/support-annotations-23.4.0.jar
         https://jitpack.io/com/android/support/support-annotations/23.4.0/support-annotations-23.4.0.pom
         https://jitpack.io/com/android/support/support-annotations/23.4.0/support-annotations-23.4.0.jar
         https://repo1.maven.org/maven2/com/android/support/support-annotations/23.4.0/support-annotations-23.4.0.pom
         https://repo1.maven.org/maven2/com/android/support/support-annotations/23.4.0/support-annotations-23.4.0.jar
         https://dl.bintray.com/drummer-aidan/maven/com/android/support/support-annotations/23.4.0/support-annotations-23.4.0.pom
         https://dl.bintray.com/drummer-aidan/maven/com/android/support/support-annotations/23.4.0/support-annotations-23.4.0.jar
         file:/C:/Users/Home/AppData/Local/Android/sdk/extras/android/m2repository/com/android/support/support-annotations/23.4.0/support-annotations-23.4.0.pom
         file:/C:/Users/Home/AppData/Local/Android/sdk/extras/android/m2repository/com/android/support/support-annotations/23.4.0/support-annotations-23.4.0.jar
         file:/C:/Users/Home/AppData/Local/Android/sdk/extras/google/m2repository/com/android/support/support-annotations/23.4.0/support-annotations-23.4.0.pom
         file:/C:/Users/Home/AppData/Local/Android/sdk/extras/google/m2repository/com/android/support/support-annotations/23.4.0/support-annotations-23.4.0.jar
     Required by:
         polar-dashboard-master:app:unspecified > com.afollestad:bridge:3.2.1
         polar-dashboard-master:app:unspecified > me.zhanghai.android.materialprogressbar:library:1.1.6
   > Could not find com.android.support:support-v4:23.4.0.
     Searched in the following locations:
         file:/C:/Program Files/Android/Android Studio/gradle/m2repository/com/android/support/support-v4/23.4.0/support-v4-23.4.0.pom
         file:/C:/Program Files/Android/Android Studio/gradle/m2repository/com/android/support/support-v4/23.4.0/support-v4-23.4.0.jar
         https://jcenter.bintray.com/com/android/support/support-v4/23.4.0/support-v4-23.4.0.pom
         https://jcenter.bintray.com/com/android/support/support-v4/23.4.0/support-v4-23.4.0.jar
         https://jitpack.io/com/android/support/support-v4/23.4.0/support-v4-23.4.0.pom
         https://jitpack.io/com/android/support/support-v4/23.4.0/support-v4-23.4.0.jar
         https://repo1.maven.org/maven2/com/android/support/support-v4/23.4.0/support-v4-23.4.0.pom
         https://repo1.maven.org/maven2/com/android/support/support-v4/23.4.0/support-v4-23.4.0.jar
         https://dl.bintray.com/drummer-aidan/maven/com/android/support/support-v4/23.4.0/support-v4-23.4.0.pom
         https://dl.bintray.com/drummer-aidan/maven/com/android/support/support-v4/23.4.0/support-v4-23.4.0.jar
         file:/C:/Users/Home/AppData/Local/Android/sdk/extras/android/m2repository/com/android/support/support-v4/23.4.0/support-v4-23.4.0.pom
         file:/C:/Users/Home/AppData/Local/Android/sdk/extras/android/m2repository/com/android/support/support-v4/23.4.0/support-v4-23.4.0.jar
         file:/C:/Users/Home/AppData/Local/Android/sdk/extras/google/m2repository/com/android/support/support-v4/23.4.0/support-v4-23.4.0.pom
         file:/C:/Users/Home/AppData/Local/Android/sdk/extras/google/m2repository/com/android/support/support-v4/23.4.0/support-v4-23.4.0.jar
     Required by:
         polar-dashboard-master:app:unspecified > com.afollestad:sectioned-recyclerview:0.2.2
   > Could not find com.android.support:support-v13:23.4.0.
     Searched in the following locations:
         file:/C:/Program Files/Android/Android Studio/gradle/m2repository/com/android/support/support-v13/23.4.0/support-v13-23.4.0.pom
         file:/C:/Program Files/Android/Android Studio/gradle/m2repository/com/android/support/support-v13/23.4.0/support-v13-23.4.0.jar
         https://jcenter.bintray.com/com/android/support/support-v13/23.4.0/support-v13-23.4.0.pom
         https://jcenter.bintray.com/com/android/support/support-v13/23.4.0/support-v13-23.4.0.jar
         https://jitpack.io/com/android/support/support-v13/23.4.0/support-v13-23.4.0.pom
         https://jitpack.io/com/android/support/support-v13/23.4.0/support-v13-23.4.0.jar
         https://repo1.maven.org/maven2/com/android/support/support-v13/23.4.0/support-v13-23.4.0.pom
         https://repo1.maven.org/maven2/com/android/support/support-v13/23.4.0/support-v13-23.4.0.jar
         https://dl.bintray.com/drummer-aidan/maven/com/android/support/support-v13/23.4.0/support-v13-23.4.0.pom
         https://dl.bintray.com/drummer-aidan/maven/com/android/support/support-v13/23.4.0/support-v13-23.4.0.jar
         file:/C:/Users/Home/AppData/Local/Android/sdk/extras/android/m2repository/com/android/support/support-v13/23.4.0/support-v13-23.4.0.pom
         file:/C:/Users/Home/AppData/Local/Android/sdk/extras/android/m2repository/com/android/support/support-v13/23.4.0/support-v13-23.4.0.jar
         file:/C:/Users/Home/AppData/Local/Android/sdk/extras/google/m2repository/com/android/support/support-v13/23.4.0/support-v13-23.4.0.pom
         file:/C:/Users/Home/AppData/Local/Android/sdk/extras/google/m2repository/com/android/support/support-v13/23.4.0/support-v13-23.4.0.jar
     Required by:
         polar-dashboard-master:app:unspecified > com.afollestad:assent:0.2.2
   > Could not find com.android.support:appcompat-v7:23.4.0.
     Searched in the following locations:
         file:/C:/Program Files/Android/Android Studio/gradle/m2repository/com/android/support/appcompat-v7/23.4.0/appcompat-v7-23.4.0.pom
         file:/C:/Program Files/Android/Android Studio/gradle/m2repository/com/android/support/appcompat-v7/23.4.0/appcompat-v7-23.4.0.jar
         https://jcenter.bintray.com/com/android/support/appcompat-v7/23.4.0/appcompat-v7-23.4.0.pom
         https://jcenter.bintray.com/com/android/support/appcompat-v7/23.4.0/appcompat-v7-23.4.0.jar
         https://jitpack.io/com/android/support/appcompat-v7/23.4.0/appcompat-v7-23.4.0.pom
         https://jitpack.io/com/android/support/appcompat-v7/23.4.0/appcompat-v7-23.4.0.jar
         https://repo1.maven.org/maven2/com/android/support/appcompat-v7/23.4.0/appcompat-v7-23.4.0.pom
         https://repo1.maven.org/maven2/com/android/support/appcompat-v7/23.4.0/appcompat-v7-23.4.0.jar
         https://dl.bintray.com/drummer-aidan/maven/com/android/support/appcompat-v7/23.4.0/appcompat-v7-23.4.0.pom
         https://dl.bintray.com/drummer-aidan/maven/com/android/support/appcompat-v7/23.4.0/appcompat-v7-23.4.0.jar
         file:/C:/Users/Home/AppData/Local/Android/sdk/extras/android/m2repository/com/android/support/appcompat-v7/23.4.0/appcompat-v7-23.4.0.pom
         file:/C:/Users/Home/AppData/Local/Android/sdk/extras/android/m2repository/com/android/support/appcompat-v7/23.4.0/appcompat-v7-23.4.0.jar
         file:/C:/Users/Home/AppData/Local/Android/sdk/extras/google/m2repository/com/android/support/appcompat-v7/23.4.0/appcompat-v7-23.4.0.pom
         file:/C:/Users/Home/AppData/Local/Android/sdk/extras/google/m2repository/com/android/support/appcompat-v7/23.4.0/appcompat-v7-23.4.0.jar
     Required by:
         polar-dashboard-master:app:unspecified > com.afollestad:assent:0.2.2
         polar-dashboard-master:app:unspecified > com.afollestad:inquiry:2.0.1
         polar-dashboard-master:app:unspecified > me.zhanghai.android.materialprogressbar:library:1.1.6
   > Could not find com.android.support:appcompat-v7:23.4.0.
     Searched in the following locations:
         file:/C:/Program Files/Android/Android Studio/gradle/m2repository/com/android/support/appcompat-v7/23.4.0/appcompat-v7-23.4.0.pom
         file:/C:/Program Files/Android/Android Studio/gradle/m2repository/com/android/support/appcompat-v7/23.4.0/appcompat-v7-23.4.0.jar
         https://jcenter.bintray.com/com/android/support/appcompat-v7/23.4.0/appcompat-v7-23.4.0.pom
         https://jcenter.bintray.com/com/android/support/appcompat-v7/23.4.0/appcompat-v7-23.4.0.jar
         https://jitpack.io/com/android/support/appcompat-v7/23.4.0/appcompat-v7-23.4.0.pom
         https://jitpack.io/com/android/support/appcompat-v7/23.4.0/appcompat-v7-23.4.0.jar
         https://repo1.maven.org/maven2/com/android/support/appcompat-v7/23.4.0/appcompat-v7-23.4.0.pom
         https://repo1.maven.org/maven2/com/android/support/appcompat-v7/23.4.0/appcompat-v7-23.4.0.jar
         https://dl.bintray.com/drummer-aidan/maven/com/android/support/appcompat-v7/23.4.0/appcompat-v7-23.4.0.pom
         https://dl.bintray.com/drummer-aidan/maven/com/android/support/appcompat-v7/23.4.0/appcompat-v7-23.4.0.jar
         file:/C:/Users/Home/AppData/Local/Android/sdk/extras/android/m2repository/com/android/support/appcompat-v7/23.4.0/appcompat-v7-23.4.0.pom
         file:/C:/Users/Home/AppData/Local/Android/sdk/extras/android/m2repository/com/android/support/appcompat-v7/23.4.0/appcompat-v7-23.4.0.jar
         file:/C:/Users/Home/AppData/Local/Android/sdk/extras/google/m2repository/com/android/support/appcompat-v7/23.4.0/appcompat-v7-23.4.0.pom
         file:/C:/Users/Home/AppData/Local/Android/sdk/extras/google/m2repository/com/android/support/appcompat-v7/23.4.0/appcompat-v7-23.4.0.jar
     Required by:
         polar-dashboard-master:app:unspecified > com.pluscubed:insets-dispatcher:0.1.3

**Comment by zdunex25** [comment]
It is not template issue it's your setup's.

**Comment by Kexagia** [comment]
Kod kurulumu?

**Comment by Kexagia** [comment]
code setup?

**Comment by afollestad** [comment]
It looks like you don't have the a Google repositories installed from the SDK Manager.

**Comment by Kexagia** [comment]
ok thanks

2016-05-26 18:32 GMT+03:00 Aidan Follestad <notifications@github.com>:
