### ISSUE TITLE
Color Changes Under Icon Details on Icon Tab

### ISSUE THREAD

**Issue by werdna3232** [afollestad/polar-dashboard#117]
Using latest Polar version, experiencing the following color changes:

![screenshot_2016-05-24-17-36-19](https://cloud.githubusercontent.com/assets/18607205/15662146/4ae9dae6-26ab-11e6-913a-238e9d006e13.png)
![screenshot_2016-05-24-17-36-23](https://cloud.githubusercontent.com/assets/18607205/15662144/4ae9a6d4-26ab-11e6-933c-85a4e0a16e09.png)
![screenshot_2016-05-24-17-36-46](https://cloud.githubusercontent.com/assets/18607205/15662145/4ae9c114-26ab-11e6-8c3c-c5f9c47dec92.png)

The dismiss coloring varies across most icons. Most of them are @color/primary_dark_material_light or @color/accent_material_light, two colors I have in my main theme. The red, however, is not related at all...

**Comment by afollestad** [comment]
The dismiss button is colored using Google's palette generator, based on the icon being displayed. So it'd be an issue on their end.
