### ISSUE TITLE
Wallpaper Issue :Force Closing 

### ISSUE THREAD

**Issue by uidhinc** [afollestad/polar-dashboard#119]
i created 2 themes with POLAR.but current theme keeps Force Closing whenever I switch Internet on.Checked everything , and everything is perfect.But when ever Data is switched on and wallpaper segment is hit..The app force closes, but with DATA off everything works perfect again.

**Comment by afollestad** [comment]
Can you get a logcat? There's not enough info here to do anything

**Comment by afollestad** [comment]
Plus you didn't follow the issue template at all, so I'm closing this issue.
