### ISSUE TITLE
appfilter/draweble problem ?

### ISSUE THREAD

**Issue by Kexagia** [afollestad/polar-dashboard#122]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [ ] I have verified that I am using the latest version of Polar Dashboard.
- [ ] I have given my issue a non-generic title.

###### Include the following:
 - Polar Dashboard version: `0.8.5.8`
 - Device OS version: `6.0.1`
 - Device Manufacturer: `Huawei`
 - Device Name: `Nexus 6P`

Please wrap Java with correct syntax highlighting.

```java
System.out.println("Hello, world!");
```

Please wrap logs with Gradle syntax highlighting (it makes them look better):

```Gradle
java.lang.RuntimeException: This is an example Exception log
    at com.afollestad.polar.ui.HelloWorld
    at com.afollestad.polar.ui.HelloWorld$ThisIsNotARealLog
    at android.app.Instrumentation.callActivityOnResume(Instrumentation.kava)
```
 
###### Reproduction Steps

1. 
2. 
3.

**Comment by Kexagia** [comment]
drawable and appfilter can not register my XML works out?

**Comment by zdunex25** [comment]
Update with your output man.

**Comment by Kexagia** [comment]
ok,thanks

2016-06-17 17:53 GMT+03:00 Kamil Z <notifications@github.com>:
