### ISSUE TITLE
Icon request tool not specific enough with appfilter.xml

### ISSUE THREAD

**Issue by OnePersonCo** [afollestad/polar-dashboard#124]
The icon request tool shows themed icons if the appfilter.xml code uses the shorthand version of the component info (1st line of code below).

Here's an example:
```xml
<item component="ComponentInfo{gov.nasa/.springboard.SpringBoardView}" drawable="nasa" />
<item component="ComponentInfo{gov.nasa/gov.nasa.springboard.SpringBoardView}" drawable="nasa" />
```

Nova Launcher provides the shorthand version (without the repetition after the slash) for developers. It is not a major issue, as I can simply write the longer version and CTRL+F "/." to find any shorthand versions, but a fix could be helpful to icon pack developers who are unaware of this issue.

Thanks in advance and have a nice day.

**Comment by afollestad** [comment]
I believe the second is much more standard than the first, and the many icon designers I've worked with closely have no problems with it.

**Comment by TWellington** [comment]
What you're suggesting may work better with Nova Launcher, but not well with other launchers. It's unnecessary for us to adjust it, unless you have more reasoning.

**Comment by OnePersonCo** [comment]
Ok, that's what I figured. Thank you for your comments!

**Comment by TWellington** [comment]
No problem, @OnePersonCo! Thanks for your feedback.
