### ISSUE TITLE
Use File Content Providers everywhere to remove the need for external storage permissions

### ISSUE THREAD

**Issue by easycheese** [afollestad/polar-dashboard#133]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Polar Dashboard.
- [x] I have given my issue a non-generic title.

Why does the user need to approve 'write_external_storage' permissions?  It seems like read would be the only one necessary.

**Comment by afollestad** [comment]
For saving and applying wallpapers.

**Comment by easycheese** [comment]
@afollestad 

I should have been more specific.  This is for the 'request icon' portion of the dashboard.

**Comment by afollestad** [comment]
Oh, it's used there too. PNGs are extracted from the system and saved into a ZIP file, which is emailed or uploaded to Polar Request Manager.

**Comment by easycheese** [comment]
Check out: http://stackoverflow.com/questions/12170386/create-and-share-a-file-from-internal-storage

and https://developer.android.com/reference/android/support/v4/content/FileProvider.html

Looks like it is possible.

**Comment by afollestad** [comment]
Yeah, I know about using Content Providers. It's just easier this way.

**Comment by afollestad** [comment]
If you'd like to make a Pull Request, go ahead, but I don't have a lot of time for non-work projects at the moment.

**Comment by easycheese** [comment]
Fair enough. Yeah I haven't the time to take it either :)

**Comment by afollestad** [comment]
I like the idea, though, so I renamed the issue and marked it as a feature :)

**Comment by PrattiDev** [comment]
Now that Polar is targeting 7.0, icon requests are broken for Nougat devices.

```Gradle
Preparing your request to send...
java.lang.Exception: Unable to create folders: /storage/emulated/0/KMZ

at com.afollestad.iconrequest.IconRequest$5.run(IconRequest.java:498)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6077)    
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```
![Error dialog](http://i.imgur.com/7TJi8RU.png)
