### ISSUE TITLE
Issue with request section info

### ISSUE THREAD

**Issue by AllanWang** [afollestad/polar-dashboard#134]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Polar Dashboard.
- [x] I have given my issue a non-generic title.

OS: 6.0.1 Marshmallow
Device: LGE Nexus 5 (du_hammerhead)
Polar version: 1.6.2 (25)

It seems as though the request section is not working properly for some apps (see screenshot). It also seems to be a bit slow, and the logs show that the UI is skipping a few frames on start. I have merely built the current source with the 24.0.1 build tools, and have not changed anything else. The improperly named icons vary each time, but the generated zip is accurate.

![screenshot_20160819-132804](https://cloud.githubusercontent.com/assets/6251823/17823686/9ddc7d20-6612-11e6-92ba-cf95e740e6ce.png)

**Comment by afollestad** [comment]
If I had to guess, it's an issue with the ROM your using. 

No one else has run into this issue. Including me on a Nexus 6P with 6.0.1 *and* 7.0.

**Comment by AllanWang** [comment]
I agree that this seems to be a weird issue. I believe back when I tested the issue happened on my emulator as well, but it doesn't seem to affect others. I don't think this makes a difference, but I modified the way the app info is pulled [here](https://github.com/AllanWang/Butler/blob/master/library/src/main/java/com/pitchedapps/butler/library/icon/request/ComponentInfoUtil.java). You may feel free to check that out, as it seems to be faster.
