### ISSUE TITLE
Easiest Method to Update Polar while keeping app mods

### ISSUE THREAD

**Issue by ItsXyzzy** [afollestad/polar-dashboard#135]
My friend made me a custom version of Polar a while ago that displays wallpapers only and I am having some issues that are fixed with more recent iterations of Polar, how can I update my dashboard to the latest version while keeping this modifications intact?

To see uses of this see [here.](https://play.google.com/store/apps/details?id=com.craigdowdall.taustakuvio)

**Comment by afollestad** [comment]
You'll have to manually put modifications back into a fresh copy of this repository.
