### ISSUE TITLE
Unable to create folders: /storage/emulated/0/polar when pressing to request icons.

### ISSUE THREAD

**Issue by OdysseasKar** [afollestad/polar-dashboard#136]
Suddenly this error pops up every time i am trying to test my app on my phone.The only files i have changed by following the guide are the drawables and appfilters xmls. This dowsnt happen when i run the polar sample app from the playstore.

 - Polar Dashboard version: `1.6`
 - Device OS version: `4.4`
 - Device Manufacturer: `HWAWEI`
 - Device Name: `Y-330`

**Comment by PrattiDev** [comment]
Here's some more info:

```D/IconRequestSend: Preparing your request to send...
W/System.err: java.lang.Exception: Unable to create folders: /data/user/0/com.kmzdsgns.kmz/cache/requests
W/System.err:     at com.afollestad.iconrequest.IconRequest$5.run(IconRequest.java:497)
W/System.err:     at android.os.Handler.handleCallback(Handler.java:751)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
W/System.err:     at android.os.Looper.loop(Looper.java:154)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6077)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```
 
###### Reproduction Steps

1. Tap on the request FAB once.
2. Wait for it to say that the requests were sent.
3. Tap on the request FAB again.

###### Expected Result

Icons requests are sent every time.

###### Actual Result

The same error as the last version of Polar, but this time, it only triggers after the first request has already been made.

**Comment by afollestad** [comment]
The latest code should fix the issue, let me know if it doesn't.

**Comment by OdysseasKar** [comment]
Updated to latest code and now the error reads: Failed to save an icon: /...png : open failed: ENOENT (no such file or directory)

**Comment by afollestad** [comment]
Pushed another update, it should definitely work now (it works on my 6P)

**Comment by afollestad** [comment]
The fastest way is to just update Icon Request

![capture](https://cloud.githubusercontent.com/assets/1820165/18594397/67f4e036-7c05-11e6-8ae8-79028b64bd02.PNG)

**Comment by OdysseasKar** [comment]
Now it says: preparing icon request..then crashes with: Unfortunately polar has stopped.

**Comment by afollestad** [comment]
It's working fine for me.

**Comment by OdysseasKar** [comment]
Could be my phone.Will test again on another one and post again

**Comment by afollestad** [comment]
Oh, thanks for the log, I know what the issue is

**Comment by afollestad** [comment]
@OdysseasKar let's hope it works now.

You'll just need to copy the changes to this file over (you can copy/paste the entire thing): https://github.com/afollestad/polar-dashboard/blob/master/app/src/main/res/xml/filepaths.xml

**Comment by OdysseasKar** [comment]
Well done! Icon request is working again and all is well in the world.

Thank you very much and have a good night.

**Comment by afollestad** [comment]
Great!

Thank you, you too

**Comment by leifniem** [comment]
Sorry for posting on a closed bug and especially sorry if this question is stupid.
I tried the fixes suggested by updating the gradle buildfile + syncing the project and am now getting the following error:

`Error:(31, 34) error: cannot find symbol class BackendConfig`

Is this an issue on my end?

Thanks in advance.

**Comment by afollestad** [comment]
You're using an older version that the previous release. Some things were renamed, you'll probably want to reimport the project.

**Comment by leifniem** [comment]
Alright, thank you very much :)
