### ISSUE TITLE
Question regarding Polar Request Manager

### ISSUE THREAD

**Issue by jahirfiquitiva** [afollestad/polar-dashboard#137]
Hi @afollestad and @TWellington

Sorry for along this here, I posted it in G+ but it seems you didn't see it.

I was wondering if you would mind if I allow IconShowcase users use Polar Request Manager... I mean, they will create an account there (paying for the service), and IconShowcase would allow them send their requests to your server.

I think I saw a post of you some time ago, saying you made an API, but I wanted to know if you're ok with that.

Thanks in advance. 😄﻿
﻿

**Comment by afollestad** [comment]
I'd like to keep it private for now

**Comment by jahirfiquitiva** [comment]
Sure, thanks anyways, Aidan. :)
