### ISSUE TITLE
Missing Intent-filter for 7.0 lockscreen wallpaper

### ISSUE THREAD

**Issue by leifniem** [afollestad/polar-dashboard#139]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Polar Dashboard.
- [x] I have given my issue a non-generic title.
###### Include the following:
- Polar Dashboard version: `1.0.10`
- Device OS version: `7.0`
- Device Manufacturer: `OnePlus`
- Device Name: `One`
###### Reproduction Steps
1. Apply wallpaper via app
2. Get Homescreen wallpaper
3. Lockscreen wallpaper remains unchanged
###### Expected Result

Lockscreen wall gets set too
###### Actual Result

It doesn't

**Comment by afollestad** [comment]
Do you know what the intent or intent filter should be? @leifniem

**Comment by leifniem** [comment]
Sadly not, but it seems to work with Candybar, so i guess you’d be able to figure it out, since you know what you’re looking for.

**Comment by afollestad** [comment]
Hmm, well I'm able to apply wallpapers to the lockscreen from Polar icon packs such as KAIP/Briq/etc.

![croppedscreenshot_1489951764594_](https://cloud.githubusercontent.com/assets/1820165/24084018/8c477b88-0cb0-11e7-903a-23f908911386.png)

You just have to select the right application after tapping "Apply".

**Comment by leifniem** [comment]
Well the issue is 5 months old, i guess it was an early nougat problem.

**Comment by afollestad** [comment]
Ah, good; we can probably close this then

**Comment by leifniem** [comment]
Absolutely :)
