### ISSUE TITLE
Can I use only the wallpaper module for my app while retaining the credit section to credit you?

### ISSUE THREAD

**Issue by rakeshg147** [afollestad/polar-dashboard#143]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [ ] I have verified that I am using the latest version of Polar Dashboard.
- [ ] I have given my issue a non-generic title.

###### Include the following:
 - Polar Dashboard version: `?`
 - Device OS version: `?`
 - Device Manufacturer: `?`
 - Device Name: `?`

Please wrap Java with correct syntax highlighting.

```java
System.out.println("Hello, world!");
```

Please wrap logs with Gradle syntax highlighting (it makes them look better):

```Gradle
java.lang.RuntimeException: This is an example Exception log
    at com.afollestad.polar.ui.HelloWorld
    at com.afollestad.polar.ui.HelloWorld$ThisIsNotARealLog
    at android.app.Instrumentation.callActivityOnResume(Instrumentation.kava)
```
 
###### Reproduction Steps

1. 
2. 
3.

**Comment by afollestad** [comment]
Yes.
