### ISSUE TITLE
Help - BuildConfig.APPLICATION_ID How to fix this ?

### ISSUE THREAD

**Issue by msay2** [afollestad/polar-dashboard#148]
What is `BuildConfig`

I use my `BuildConfig` 
but `APPLICATION_ID` is not found

How to fix this

**Comment by afollestad** [comment]
Android Studio generates that class when you build the project.

**Comment by msay2** [comment]
Thank you for your reply. 😉

I just noticed, Android Studio generates it to me alone but does not generate
```
public static final String APPLICATION_ID = "com.mycompany.myapp" ;
```
So I put it in my java file `AdapterApply.java`.

Thanks Aidan !
