### ISSUE TITLE
The icons do not apply via my project or via Polar

### ISSUE THREAD

**Issue by msay2** [afollestad/polar-dashboard#149]
[The](url) icons do not apply via my project or via Polar

- [√ ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [√ ] I have verified that I am using the latest version of Polar Dashboard.
- [ √] I have given my issue a non-generic title.

###### Include the following:
 - Polar Dashboard version: `1.8.1`
 - Device OS version: `6.0.1` (CyanogenMod)
 - Device Manufacturer: `?`
 - Device Name: `Galaxy Ace II GT-I8160P`

###### Expected Result
- Applying icons !

###### Actual Result
- No icons are applied !

###### Additional message
- No icons are applied via my project, I checked to have everything respected, but the icons do not apply.So I tried directly by Polar but even on the Polar project the icons do not apply. (On the other hand via CyanogenMod it works perfectly). (My launcher is Nova).

**Comment by TWellington** [comment]
What do you mean applying directly by Polar? If you're talking about
applying the Polar sample project, that's because there is no appfilter to
apply the icons.

**Comment by msay2** [comment]
I now understand why on Polar this did not work.

But I have exactly the same problem on my project, yet my appfilter.xml is in my `xml` and `assets` folder and yet the icons do not apply.

CyanogenMod works very well ... but that's when I get stuck! ... my application arrives to apply the icons for CyanogenMod, in this case the appfilter.xml is found, but for NovaLauncher is different, I have the impression that it ignores the appfilter.xml and does not apply anything at all

**Comment by TWellington** [comment]
Have you tried restarting Nova? Are you in the beta program? If you are, I
would advise 2 things: 1) uninstalling and reinstalling, and 2) unenroll
from the beta program if that doesn't work. If that's not the issue, I
would try using another launcher and seeing if you have the same problem.
If you don't - it must be a Nova issue. If you do, then it must be on your
end.

**Comment by msay2** [comment]
I uninstalled and reinstalled my application, I used another launcher (ADW), I restarted NovaLauncher several times, no difference the icons does not apply yet.

For the beta program I do not see what you want to speak

**Comment by msay2** [comment]
Hello
I settled my problem !!

Instead of writing:
```
<item component="ComponentInfo{com.mycompany.myapp/com.mycompany.myapp.MainActivity}" drawable="ic_launcher"/>
```
I wrote:
```
<item component="ComponentInfo{com.mycompany.myapp}" drawable="ic_launcher"/>
```
Without realizing it I neglected the package path to the main activity of the concerned application! (😒)

Thank you for your answers @TWellington

**Comment by TWellington** [comment]
You're welcome! I'm glad it worked out for you.
