### ISSUE TITLE
Icon request "backend"

### ISSUE THREAD

**Issue by plusCubed** [afollestad/polar-dashboard#15]
https://plus.google.com/111080505870850761155/posts/LkNcyi6X8Nh

One way to do this is Google Sheets. It'd be a great for icon pack designers to have a chronologically-ordered request Google Sheet with number of requests for each package, etc. There are some problems with the logistics though - the sheet would have to be publicly editable, making it vulnerable to malicious intents (if anyone bothers to dig up the ID).

Another way to approach this is perhaps have a Firebase database set-up - the designer would have to open an account to do this though. With properly written security rules (which we can write up and have the designer copy in), the icon requests can contain package name, appfilter, number of requests, emails (hidden from public), notes, etc. It's all just JSON though, which isn't nice to look at, so a web portal where a designer can look up their requests (the publicly available info) with their Firebase ID would be needed.

Those are just two approaches I thought of. I'm personally liking the Firebase approach since it wraps up all the loose ends I see, and won't require too much work on the designer's part if everything is engineered correctly. I can start working on that if you guys think it's good (along with #10)

**Comment by danielhickman** [comment]
It could send the request data to a PHP or NodeJS script that interacts with the authenticated designer's Google Drive. Slightly more complicated (mainly with the tokens and such), but wouldn't require others to get a Firebase.

**Comment by afollestad** [comment]
I was thinking about Node.js, but I decided Firebase was better since they the DB for you and they have a free tier. Working on it now.

**Comment by afollestad** [comment]
Actually I think I'll go with Node.js for simplicity and the least amount of mobile-side code. We'll just need a good hosting solution for people who don't have their own servers.

**Comment by danielhickman** [comment]
Paid requests would also be a good idea. It should be price per icon and be listed online higher.

**Comment by TWellington** [comment]
Paid requests won't be implemented by us.

**Comment by afollestad** [comment]
This is very, very close to being down now. @plusCubed and @PDDStudio, I gave you access to the repository.

It's a full backend UI with API access.

**Comment by afollestad** [comment]
This is pretty much done now.

Preview: https://plus.google.com/+AidanFollestad/posts/dpJendbfRqW

(for those who aren't using the private beta already)
