### ISSUE TITLE
Want to make a kwgt widget pack using polar dashboard but unable to delete and create tabs

### ISSUE THREAD

**Issue by Aditya-1811** [afollestad/polar-dashboard#150]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Polar Dashboard.
- [ ] I have given my issue a non-generic title.

###### Include the following:
 - Polar Dashboard version: `?`
 - Device OS version: `7.1.1`
 - Device Manufacturer: `Oneplus`
 - Device Name: `3t`

Please wrap Java with correct syntax highlighting.

```java
System.out.println("Hello, world!");
```

Please wrap logs with Gradle syntax highlighting (it makes them look better):

```Gradle
java.lang.RuntimeException: This is an example Exception log
    at com.afollestad.polar.ui.HelloWorld
    at com.afollestad.polar.ui.HelloWorld$ThisIsNotARealLog
    at android.app.Instrumentation.callActivityOnResume(Instrumentation.kava)
```
 
###### Reproduction Steps

1. 
2. 
3.

**Comment by Aditya-1811** [comment]
want a kwgt widget pack dashboard without the icon tab but can anyone please tell me what to delete inorder to get it done, like hich layout and which part of the activity to edit?

**Comment by afollestad** [comment]
Polar is designed to be for icon packs primarily, so I do not plan to change that in the main source.

You can remove tabs from `MainActivity.java` though.

**Comment by PDDStudio** [comment]
For further interest (and people who don't know how to code / are to lazy):

[My fork](https://github.com/PDDStudio/polar-dashboard) has this changes for the mentioned use case.
