### ISSUE TITLE
The icons dont apply in any launcher I choose

### ISSUE THREAD

**Issue by Luismi74** [afollestad/polar-dashboard#153]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Polar Dashboard.
- [x] I have given my issue a non-generic title.

###### Include the following:
 - Polar Dashboard version: `1.8.1`
 - Device OS version: `6.0.0`
 - Device Manufacturer: `Blu`
 - Device Name: `Blu Life one X2`

###### Reproduction Steps

1. I compiled my app and 0 errors
2. All app filters and drawable files are correctly filled
3. installed on my cell phone and hit apply with nova, adw and aviate.

###### Expected Result
get my icons themed

###### Actual Result
none, but I can select them from edit mode with nova, shows all the icons. doesn't apply them, not even one icon

**Comment by Luismi74** [comment]
![screenshot_20170415-001325 1](https://cloud.githubusercontent.com/assets/15695141/25060672/9daf29e6-2170-11e7-8569-90876161245d.png)
![screenshot_20170415-001325 1](https://cloud.githubusercontent.com/assets/15695141/25060675/a3745df6-2170-11e7-8d35-65527443c2b3.png)
![screenshot_20170414-234927 1](https://cloud.githubusercontent.com/assets/15695141/25060678/b668017e-2170-11e7-8aff-2a6894fa8335.png)

**Comment by afollestad** [comment]
Since Polar is contacting Nova successfully there, it's either a problem with your configuration or Nova. But it's not something I can fix on my end.

**Comment by afollestad** [comment]
You're probably using an invalid appfilter.xml file or something.

**Comment by Luismi74** [comment]
I'm using the same format as yours, Example:
<item component="ComponentInfo{ com.nfl.fantasy.core.android/com.nfl.fantasy.core.android.activities.MainActivity}" drawable="___nfl_fantasy"/>

Question, what is the file where has the info of the launchers?

**Comment by Luismi74** [comment]
`<item component="ComponentInfo{ com.nfl.fantasy.core.android/com.nfl.fantasy.core.android.activities.MainActivity}" drawable="___nfl_fantasy"/>`

**Comment by Luismi74** [comment]
couldnt find the error, still looking

**Comment by Luismi74** [comment]
couldnt find the error, still looking

**Comment by Luismi74** [comment]
it was a space more in the appfilter, all done! thanks
