### ISSUE TITLE
Polar crash when kwgt is not installed

### ISSUE THREAD

**Issue by marcogenovese** [afollestad/polar-dashboard#154]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Polar Dashboard.
- [x] I have given my issue a non-generic title.

###### Include the following:
 - Polar Dashboard version: `1.9.0`
 - Device OS version: `7.0`
 - Device Manufacturer: `Huawei`
 - Device Name: `VNS L31`
 
###### Reproduction Steps

1. Launch Polar Dashboard
2. Go to Kustom tab
3. Tap a widget

###### Expected Result
Ask to install KWGT, link to PlayStore

###### Actual Result
Crash

**Comment by frmz** [comment]
Confirmed, will fix
