### ISSUE TITLE
Changing the icons on the tab (home,wallpapers,zooper,about)

### ISSUE THREAD

**Issue by Aditya-1811** [afollestad/polar-dashboard#156]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Polar Dashboard.
- [x] I have given my issue a non-generic title.

###### Include the following:
 - Polar Dashboard version: `1.9.0`
 - Device OS version: `7.1.2`
 - Device Manufacturer: `Oneplus`
 - Device Name: `3t`

Please wrap Java with correct syntax highlighting.

```java
System.out.println("Hello, world!");
```

Please wrap logs with Gradle syntax highlighting (it makes them look better):

```Gradle
java.lang.RuntimeException: This is an example Exception log
    at com.afollestad.polar.ui.HelloWorld
    at com.afollestad.polar.ui.HelloWorld$ThisIsNotARealLog
    at android.app.Instrumentation.callActivityOnResume(Instrumentation.kava)
```
 
###### Reproduction Steps

1. 
2. 
3. 

###### Expected Result
wanted to change the home,wallpapers,about and zooper tab icons. Replaced the home and zooper ones with mine and should have changed. Also i can't find wallpaper and about tab icons

###### Actual Result
Nothing changed , the icons remained the same

**Comment by PDDStudio** [comment]
As an alternative you can put your icons into `res/drawables/` and then replace them in Polar's [setup method](https://github.com/afollestad/polar-dashboard/blob/master/app/src/main/java/com/afollestad/polar/ui/MainActivity.java#L195).
Search for your target drawable(s) ( referenced via `R.drawables.some_name` ) and replace them with your drawable's name.

**Comment by Aditya-1811** [comment]
Thanks man. Btw I got this a long time ago 😃

**Comment by PDDStudio** [comment]
Alright great. I'm going to close this issue then.

**Comment by Aditya-1811** [comment]
OK. BTW remember me?
