### ISSUE TITLE
[Request]showing icons name to users would make relocating them inside the icon pack very easy. Thanks.

### ISSUE THREAD

**Issue by BasemAlMoudares** [afollestad/polar-dashboard#159]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Polar Dashboard.
- [x] I have given my issue a non-generic title.

###### Include the following:
 - Polar Dashboard version: `?`
 - Device OS version: `?`
 - Device Manufacturer: `?`
 - Device Name: `?`

Please wrap Java with correct syntax highlighting.

```java
System.out.println("Hello, world!");
```

Please wrap logs with Gradle syntax highlighting (it makes them look better):

```Gradle
java.lang.RuntimeException: This is an example Exception log
    at com.afollestad.polar.ui.HelloWorld
    at com.afollestad.polar.ui.HelloWorld$ThisIsNotARealLog
    at android.app.Instrumentation.callActivityOnResume(Instrumentation.kava)
```
 
###### Reproduction Steps

1. 
2. 
3.

**Comment by afollestad** [comment]
Icon names are shown when tapped.

**Comment by BasemAlMoudares** [comment]
Hey Aidan, showing icons name in its containers even before tapping any icon is to sort them alphabetically so users can then be able to locate icon they saw a minute back in a list of more than 100 icons, and then you can remove showing icons name after tapping them. Thanks for your time.
