### ISSUE TITLE
Toolbar title sometimes gets cut off with ellispsis

### ISSUE THREAD

**Issue by afollestad** [afollestad/polar-dashboard#16]
Happens randomly, restarting the app always solves the issue.

**Comment by afollestad** [comment]
![screener_20160201 19-45-19](https://cloud.githubusercontent.com/assets/1820165/12737236/679d4ca0-c91c-11e5-9dd9-3a457c601102.png)

**Comment by afollestad** [comment]
@plusCubed have you ever seen this before?

I'm wondering if we could solve this problem by using a custom TextView inside the Toolbar for the title.

**Comment by plusCubed** [comment]
There has also been problems with toolbar icons disappearing occasionally. I think it's something with the logic/timing of showing/hiding the toolbar items, which causes that and this issue.

**Comment by afollestad** [comment]
I believe it's fixed, will re-open if that's not the case

**Comment by crutchcorn** [comment]
I am experiencing this bug with 7f19698e3046b5d4845374f279b91077905b5036

**Comment by crutchcorn** [comment]
@afollestad, I have had this happen with two separate builds of Polar. One that was upgraded with PUT and the other right from source (see commit above). Just thought I'd let you know the conditions to save you a little testing :) If you did already test, are you able to confirm?

**Comment by afollestad** [comment]
Thanks for the info!

This issue is very weird and annoying
