### ISSUE TITLE
Window insets occasionally not applied

### ISSUE THREAD

**Issue by afollestad** [afollestad/polar-dashboard#17]
The home FAB sometimes goes under the nav bar. Restarting the app solves the problem.

**Comment by jahirfiquitiva** [comment]
This may help (directly taken from IconShowcase, you may need to edit it a bit)

```
<android.support.design.widget.FloatingActionButton
        android:id="@+id/fab"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="end|bottom"
        android:layout_margin="@dimen/cards_padding"
        android:src="@drawable/ic_action_star"
        app:backgroundTint="@color/accent"
        app:fabSize="normal"
        app:rippleColor="@color/semitransparent_white"/>
```

**Comment by afollestad** [comment]
We use window insets, since not all decides have a navigation bar. But the code sometimes doesn't work for some reason. @plusCubed may be able to figure it out.

**Comment by afollestad** [comment]
@plusCubed you said this was fixed now from the other issue, right?

**Comment by plusCubed** [comment]
@afollestad I'm playing around with the app, and it seems like this is a problem with the window insets (or how we're doing it) - it sometimes doesn't get applied. I'm going to rename this issue and merge the other one into this. My initial guess is it's the ViewPager.

**Comment by plusCubed** [comment]
Related?... [this](https://code.google.com/p/android/issues/detail?can=2&start=0&num=100&q=&colspec=ID%20Type%20Status%20Owner%20Summary%20Stars&groupby=&sort=&id=180492) & [this](http://stackoverflow.com/questions/31577131/coordinatorlayout-status-bar-padding-disappears-during-fragment-transactions?lq=1), no working solutions presented though.

**Comment by afollestad** [comment]
@plusCubed it looks like one of those comments have a possible workaround,

If it is a bug, we might need a way to handle the padding with insets.

**Comment by afollestad** [comment]
Sorry, without*

**Comment by plusCubed** [comment]
Just using the Activity ones might work - trying...

**Comment by afollestad** [comment]
I hope so! It's the last major "bug" now

**Comment by plusCubed** [comment]
Pushed - it seems to work much better with the Activity insets - but occasionally still not applied, presumably because the insets aren't set in the Activity yet. The Fragments will have to save a list of which views need to have insets apply, then do so when the insets are ready.

**Comment by afollestad** [comment]
So will we have a permanent solution for this?

**Comment by plusCubed** [comment]
Working on a solution involving custom Views (to support 4.4 transparent status/nav bar as well) - going to make it into a library if it works well enough.

**Comment by afollestad** [comment]
That sounds great!

**Comment by afollestad** [comment]
Hopefully this will be included in those fixes too: https://plus.google.com/+HadifHatta/posts/3JZ66i9wYmR

(I'm assuming it will be since it appears to be related?)

**Comment by afollestad** [comment]
I think I'm gonna need to just remove insets altogether and switch to explicit padding so I can get a release out to everyone that's using the dashboard sooner than later

**Comment by plusCubed** [comment]
@afollestad I agree, that's probably best for now. I do want to get this working though because the explicit padding method causes issues with some devices as well.

**Comment by afollestad** [comment]
Yeah, the workarounds actually workout pretty well. The code is live now.

**Comment by afollestad** [comment]
I'll close this for now since the workaround is working
