### ISSUE TITLE
Bottom inset sometimes isn't applied to the about section list

### ISSUE THREAD

**Issue by yadesign** [afollestad/polar-dashboard#18]
bottom card hides behind navbar, can't tap any links on it

**Comment by afollestad** [comment]
This is related to https://github.com/afollestad/polar-dashboard/issues/17, it only happens sometimes on my end. Still looking into it.

**Comment by yadesign** [comment]
seems like it's related to nav drawer mode

**Comment by plusCubed** [comment]
#17
