### ISSUE TITLE
Severe landscape issues

### ISSUE THREAD

**Issue by afollestad** [afollestad/polar-dashboard#19]
![screenshot_20160131-201610](https://cloud.githubusercontent.com/assets/1820165/12707274/9266aae6-c857-11e5-8567-c6f8b535a13d.png)

Partly related to insets by the looks of it. Like #17, #18 (not #16).

@plusCubed do you have any ideas on how to fix some of these inset issues?

**Comment by plusCubed** [comment]
It probably has to do with the insets being preserved as static.

**Comment by afollestad** [comment]
@plusCubed I removed that just now actually, but the problem persists :o

**Comment by plusCubed** [comment]
Fixed, along with the homepage padding

**Comment by afollestad** [comment]
Great, thanks!
