### ISSUE TITLE
Tapping a wallpaper to load it full-size, results in the status bar color changing to blue on the dark theme

### ISSUE THREAD

**Issue by ryanmkelly** [afollestad/polar-dashboard#20]
![2016-02-01 11 12 33](https://cloud.githubusercontent.com/assets/5175919/12715887/bd3e1fe2-c8d4-11e5-882c-ae77741db3e7.png)

"default_primarydark_lighttheme" is the colour it matches to.

**Comment by afollestad** [comment]
This will be fixed shortly, thanks

**Comment by afollestad** [comment]
It should be fixed in the code base, it was a pretty quick fix.

You can just copy the contents of [WallpapersFragment.java](https://github.com/afollestad/polar-dashboard/blob/master/app/src/main/java/com/afollestad/polar/fragments/WallpapersFragment.java) into your app to patch it.

**Comment by ryanmkelly** [comment]
awesome, ty.
