### ISSUE TITLE
Separate Drawable.xml file for the Dashboard

### ISSUE THREAD

**Issue by MaximilianKeppeler** [afollestad/polar-dashboard#21]
Is it possible to use two different `drawable.xml`'s? One for the Icon Picker and one for Dashboard? 

It seems like my users don't want to miss the A-Z grouping for icons in the Icon Picker (Since there is no  way to search for icons). But it would be unbelievable stupid to make them for the Dashboard too, because there users have a search function. 

### So overall:

`drawable.xml`: Which launchers are using and where you can add much more categories so users can find the icons faster.

`drawable_dashboard.xml`: Which uses the Dashboard and where I can use less categories since there is a search function included in the icon pack.

Thanks in advance,

Maximilian Keppeler

**Comment by afollestad** [comment]
Added to the code base ☺

**If** you add a `drawable_dashboard.xml` file in `/res/xml`, the dashboard will use that file instead of `drawable.xml` in the UI. The other is still needed as I'm sure you know.

**Comment by afollestad** [comment]
Information was added here too: http://afollestad.github.io/polar-dashboard/importingyouricons.html

**Comment by MaximilianKeppeler** [comment]
Jep, thank you very much! :)
