### ISSUE TITLE
Support for icon picker intents

### ISSUE THREAD

**Issue by MaximilianKeppeler** [afollestad/polar-dashboard#22]
A Shortcut in some Launcher's Icon Pickers would lead the user to the Dashboard Icons Section, where he is able to use the search function. He can easily and fast find the icon and apply it directly by clicking on the icon. 

Demonstration of this function:
[https://drive.google.com/file/d/0B6ky9fzTGl9XZktsdWl2NzNUYU0/view?usp=sharing](url)

It's very useful, I hope you will be able to add it! :+1: 

Best regards,

Maximilian Keppeler

Note: this is needed for Apex launcher?

**Comment by afollestad** [comment]
I think this is actually already implemented but it might not be working correctly, I'll double check later when I'm not wowrking

**Comment by afollestad** [comment]
Hmm, I'm actually not able to find this functionality in Nova or Action Launcher (since they both handle icon picking on their own). Action Launcher is especially good at icon picking now.

**Comment by MaximilianKeppeler** [comment]
I just know about this shortcut in the Nova Launcher's Icon Picker. 

Since you have added the dashboard_drawable.xml, this will not be a big issue anymore. I will just order it better for the launchers, where users can't search for icons. Thanks!

**Comment by TWellington** [comment]
@afollestad I'm actually pretty sure this is necessary for people to apply icons manually with Apex Launcher.

**Comment by danielhickman** [comment]
+1

**Comment by afollestad** [comment]
I'll have to find documentation for how this is done somewhere.

**Comment by afollestad** [comment]
Does anyone know exactly how this is done? Unfortunately it's hard to find documentation on this kind of stuff.

We're very close to the next release of Polar, along with the new upgrade tool.

**Comment by TWellington** [comment]
Have you tried contacting the developer of Apex? You could also try to get
in touch with Dani Mahardhika.

https://plus.google.com/+DaniMahardhika/posts

**Comment by afollestad** [comment]
Can someone check if it works with the latest code? I made some changes earlier related to this.

Also, Zooper support was just pushed.

**Comment by afollestad** [comment]
It appears Apex recognizes it now. But, I noticed there is some configuration files which people most likely forgot to change since they are not listed on our web guide right now.

It results it Apex thinking the sample is called Moonshine, lol.

**Comment by afollestad** [comment]
Added info about these 4 files here: http://afollestad.github.io/polar-dashboard/gettingstarted.html#metadata

The upgrade tool will handle filling these in correctly if you use it to upgrade to the next version, when it's ready.
