### ISSUE TITLE
SearchView should adapt its text color to the primary theme color

### ISSUE THREAD

**Issue by TWellington** [afollestad/polar-dashboard#24]
The search text is seemingly un-editable. I haven't been able to find that hex code in MainActivity or in the individual fragments, or in colors.xml.

**Comment by afollestad** [comment]
Updated the title, since the text color should automatically be generated based on their primary theme color (so less configuration is required)

**Comment by afollestad** [comment]
Now matches the tab icon color, like the toolbar title does
