### ISSUE TITLE
Request section sometimes shows themed apps?

### ISSUE THREAD

**Issue by TWellington** [afollestad/polar-dashboard#25]
For some reason, some devs are reporting that even themed apps are showing up in the request section, even when both appfilters are filled out.

**Comment by afollestad** [comment]
You should be more specific with your titles, lol

**Comment by ryanmkelly** [comment]
I had the same issue until I put the app filter into the assets folder (forgot the first time round), since then I haven't seen any issues.

**Comment by TWellington** [comment]
@afollestad ;)
@ryanmkelly then my informants were incorrect. I don't have the issue either, but people complained.

**Comment by afollestad** [comment]
Wait, so can this issue be closed, then?
