### ISSUE TITLE
Without the storage permission, the icon requests tab lags while swiping

### ISSUE THREAD

**Issue by jereksel** [afollestad/polar-dashboard#26]
Sometimes you have to swipe multiple times to move to next/previous tab.

**Comment by afollestad** [comment]
Good find, thanks

**Comment by jereksel** [comment]
Do we really need storage permission to begin with (I see it's used to save some .zip file - we can save it in internal storage without permissions)?

**Comment by afollestad** [comment]
In order for a mail client like Gmail to use it as an attachment, it needs to be in external storage

**Comment by afollestad** [comment]
Seems to be fixed now
