### ISSUE TITLE
Donation feature support

### ISSUE THREAD

**Issue by link6155** [afollestad/polar-dashboard#30]
Allow theme creators to implement a donation feature using in-app purchase.

**Comment by ryanmkelly** [comment]
+1 for this on my end as well.

**Comment by yadesign** [comment]
indeed, that would be useful

**Comment by afollestad** [comment]
Added 

![screener_20160204 15-38-15](https://cloud.githubusercontent.com/assets/1820165/12830538/69bb6036-cb55-11e5-8567-d36d2694d837.png)

**Comment by afollestad** [comment]
Added some details to http://afollestad.github.io/polar-dashboard/customization.html
