### ISSUE TITLE
Issues related to permission requests

### ISSUE THREAD

**Issue by PDDStudio** [afollestad/polar-dashboard#31]
- Why is the app immediately asking for permission on it's startup?
- When downloading a wallpaper and granting permission the download doesn't start immediately, you have to press download again to save the wallpaper

**Comment by afollestad** [comment]
The FAB under the nav bar bug is related to an already open issue. 

It needs the permission in the icon requests tab which loads immediately on startup, it'd probably work to request the permission during an actual request. 

The lag after denying permission has already been fixed and pushed earlier today. 

I'll look into that.

**Comment by afollestad** [comment]
Updated the original issue to reflect what's already been fixed

**Comment by afollestad** [comment]
Everything related to this issue should be fixed now
