### ISSUE TITLE
Notification bar is overlapping the app in my Redmi 1s (Kitkat)

### ISSUE THREAD

**Issue by mddanishansari** [afollestad/polar-dashboard#32]
![image](https://cloud.githubusercontent.com/assets/11080523/12745323/adcfaf2c-c9be-11e5-978a-54c04d34fe71.png)

**Comment by afollestad** [comment]
@plusCubed could this be an OS (ROM) bug related to insets?

We might need a solution that involves not using inset checks at all.

**Comment by afollestad** [comment]
#17
