### ISSUE TITLE
Bug Report / Feedback Function

### ISSUE THREAD

**Issue by MaximilianKeppeler** [afollestad/polar-dashboard#34]
A Bug Report/ Feedback, or however you want to call it, function in the settings would be nice. So users inform me fast about any issues or when they want to get it touch fast per E-Mail. 

When they press the option, a mail will be generated with the subject line "Bug Report/ Feedback". Then they can write their two cents and send it. I have seen such functions build in the apps, but imo this would already be enough.

**Comment by afollestad** [comment]
Added 

![screener_20160204 15-38-15](https://cloud.githubusercontent.com/assets/1820165/12830538/69bb6036-cb55-11e5-8567-d36d2694d837.png)

**Comment by afollestad** [comment]
Added some details to http://afollestad.github.io/polar-dashboard/customization.html

**Comment by MaximilianKeppeler** [comment]
Thanks for that too. You are awesome.
