### ISSUE TITLE
LG Home support

### ISSUE THREAD

**Issue by zavukodlak** [afollestad/polar-dashboard#35]
Support for LG Home launcher

**Comment by MaximilianKeppeler** [comment]
Regarding the Poll I made on Google Plus, it seems like not many LG Home launcher users are on Google Plus. Now I get daily up to 10 mails for adding the LG Home launcher back. -_-

**Comment by afollestad** [comment]
I believe LG Home will now see packs using Polar.

Not sure if @TWellington wants to add an option within the dashboard or not.

**Comment by TWellington** [comment]
@afollestad might as well! I can work on that. Do we know that it works?

**Comment by afollestad** [comment]
Sweet, we'll just need an icon. 

I'm sure I can find the necessary apply intent somewhere.

**Comment by afollestad** [comment]
And yeah I think Kevin said something about it working in KAIP at some point

**Comment by afollestad** [comment]
Not entirely done yet, re-opening

**Comment by afollestad** [comment]
@TWellington did you ever ask Kevin about this?

**Comment by afollestad** [comment]
@plusCubed would you happen to know of any extras needed for LG Home support?

**Comment by plusCubed** [comment]
@afollestad Not really knowledgeable on this matter, no.

**Comment by afollestad** [comment]
@plusCubed no worries!

It appears @TWellington has figured it out, a new release will be available shortly.
