### ISSUE TITLE
Shared element transition bugs in the wallpaper viewer

### ISSUE THREAD

**Issue by afollestad** [afollestad/polar-dashboard#41]
If you open a wallpaper, swipe to a different one, and close it, it will use the first wallpaper you viewed when displaying the close animation.

Similar logic to Impression's image viewer should be used.

**Comment by afollestad** [comment]
@plusCubed this may be something you could fix quickly?

**Comment by afollestad** [comment]
Would you mind looking at this whenever you have some time, @plusCubed?

**Comment by afollestad** [comment]
I hope to have this done for milestone 1.6

**Comment by plusCubed** [comment]
Done. Also added a little animation to the Toolbar.
