### ISSUE TITLE
Option to opt-out of light status bar mode

### ISSUE THREAD

**Issue by MaximilianKeppeler** [afollestad/polar-dashboard#45]
The notification bar Icons are black/ dark. Is there a option to make them white again? 

In my opinion it looks much better, even with the dark theme. The notification bar icons are also dark when the theme is light.

**Comment by MaximilianKeppeler** [comment]
lol found the option. Sorry.

**Comment by afollestad** [comment]
Not 100% sure what you mean with the original comment.

It will use light status bar mode (dark icons) if the status bar color is light, currently. You want to disable that?

**Comment by MaximilianKeppeler** [comment]
Well, I use now Amber 600 for the status bar and the statusbar icons keep being black. I don't know if it is possible to add a option to keep them white (in the dark and light theme). It just doesn't really look nice.

**Comment by afollestad** [comment]
Added options to `dev_theming.xml` :)

**Comment by MaximilianKeppeler** [comment]
That's great, thank you!
