### ISSUE TITLE
[Feature Request] [Get Rid of Wallaper Section]

### ISSUE THREAD

**Issue by Beasto** [afollestad/polar-dashboard#46]
Can we have a variable in dev_options to disable the wallpaper section just like we have for the home screen and the Zooper Widgets

**Comment by TWellington** [comment]
It's easy enough to do through code (I'd assume, it was easy enough to
remove stuff when I used PaperBoard), but we could work on it.

**Comment by afollestad** [comment]
Yeah, it requires one line to be removed in MainActivity

**Comment by afollestad** [comment]
Leaving `wallpapers_json_url` empty will disable this page, now
