### ISSUE TITLE
Fragment Toolbar icon tinting issue

### ISSUE THREAD

**Issue by Kingsman786** [afollestad/polar-dashboard#47]
The select all icon in the Requests Page is not colored with rest of the toolbar icons.

It's noticeable if you change the tint color to something that isn't white.

**Comment by afollestad** [comment]
Updated your description a bit. Thanks!

**Comment by afollestad** [comment]
I'm surprised I didn't notice this before, it was a pretty obvious bug. Fixed!

**Comment by Kingsman786** [comment]
Thanks! That was quick! :)
