### ISSUE TITLE
AppBar shadow appears below icon drawables in dedicated view

### ISSUE THREAD

**Issue by PrattiDev** [afollestad/polar-dashboard#48]
Title is pretty much self-explanatory.

When looking at a dedicated page for icons - All Icons, Google Icons, etc - the AppBar shadow is drawn below the icon drawables instead of above them. This doesn't seem to take effect anywhere else in the dashboard. 

![2016-02-08](https://cloud.githubusercontent.com/assets/1820165/12900809/d1151b8e-ce7d-11e5-9da3-8779761ee5d4.png)

**Comment by TWellington** [comment]
#KMZconfirmed

**Comment by afollestad** [comment]
Hmm, it turns out this is due to how the 'More' activity is setup for shared element transitions (the slide up and reveal animation).

I'll have to come up with a workaround for this. 

@plusCubed
