### ISSUE TITLE
Multiple cards support

### ISSUE THREAD

**Issue by crutchcorn** [afollestad/polar-dashboard#50]
My icon pack is an open source project and I would like to add a card for all of the team members. Am I missing something or is there no way to do this?

**Comment by PDDStudio** [comment]
This wasn't possible yet. A pull request #51 is already opened.

**Comment by afollestad** [comment]
Thanks @PDDStudio! I'll test this a bit and add migration to PUT

**Comment by afollestad** [comment]
I actually just completely redid this system. You can now add additional cards and additional buttons to each card all from `dev_about.xml`. No additional layouts or anything are required.

![capture](https://cloud.githubusercontent.com/assets/1820165/12960480/1d9131da-d001-11e5-8ddc-b1c1d4966f7b.JPG)
