### ISSUE TITLE
Wallpaper Isuue

### ISSUE THREAD

**Issue by mddanishansari** [afollestad/polar-dashboard#54]
**There is simple issue when we save wallpapers.**

**For example**
Wallpaper extension: jpeg
Wallpaper: Wallpaper 152
Author: MD Danish Ansari

So when we save this wallpaper it is saving as **Wallpaper_152_MD Danish_Ansari..jpeg**
**Notice the two dots before jpeg**

Also why when we just apply wallpaper it is saving wallpaper also.

So when we download wallpaper then we have two same wallpapers in Gallery.

**Comment by mddanishansari** [comment]
Not a big issue. I solved it myself by editing one line WallpaperUtils.java

**Comment by afollestad** [comment]
Fixed the double-period issue. 

Regarding saving the wallpapers, that's necessary since a file name is given to launchers when setting the wallpaper.
