### ISSUE TITLE
Weird issue in the More Icons screen on pre-L

### ISSUE THREAD

**Issue by mddanishansari** [afollestad/polar-dashboard#55]
There is some issues in the toolbar in the icons preview activity. I don't know what to call it, but there is problem.

You'll notice it in the 2nd screenshot. I'm using a Redmi 1s.

![untitled-2](https://cloud.githubusercontent.com/assets/11080523/12971523/0c152382-d0c2-11e5-8c62-c4b1be114829.png)

**Comment by afollestad** [comment]
@plusCubed any ideas? Could this be from the shared transition?

**Comment by afollestad** [comment]
It's very likely it's related to the software (OS) you're running on that device.

I've actually never heard of Redmi, and I'm unable to reproduce these issues on stock Android.

**Comment by afollestad** [comment]
Oh I'm actually able to reproduce it on stock KitKat. Looks like another issue related to those shared element transition views has popped up @plusCubed  :o

**Comment by afollestad** [comment]
Was simpler than I thought, fixed.
