### ISSUE TITLE
Generate Zooper Widget Previews

### ISSUE THREAD

**Issue by afollestad** [afollestad/polar-dashboard#56]
Rather than making designers include preview images.

It's actually very easy, and basically done now. Just needs some final adjustments and testing.

**Comment by afollestad** [comment]
Done in the code

**Comment by PDDStudio** [comment]
Are you extracting the image out of the .zw template or do you use anything else to generate the preview image? In case you're extracting the preview image you might want to have a look at [this](https://github.com/PDDStudio/ZooperUtils/blob/master/library/src/main/java/com/pddstudio/zooperutils/utils/BitmapUtils.java#L13). Maybe you want to add an option to remove the grey background from the image.

**Comment by afollestad** [comment]
We used that but it was removed yesterday since some widgets use that color. 

There's a way to make previews have a transparent background when they are built into zw files, as mentioned on the web guide 😉

**Comment by afollestad** [comment]
The previews are PNGs pulled out of the .zw file (which is a ZIP archive)
