### ISSUE TITLE
Issues when a lot of tabs are enabled in landscape

### ISSUE THREAD

**Issue by afollestad** [afollestad/polar-dashboard#57]
Tabs should go to the second line in landscape *if* there are a certain amount of tabs.

**Comment by afollestad** [comment]
![screenshot_20160212-232725](https://cloud.githubusercontent.com/assets/1820165/13026075/a0c2ee00-d1e0-11e5-9f00-a63a07d0b269.png)

**Comment by plusCubed** [comment]
If title truncated -> second line tabs. I think I've done the title truncation detection in another app (not sure which, going to have to find it).

**Comment by plusCubed** [comment]
6a4e8f06903eaadaf1290a033f0cfde95ab9211f

**Comment by afollestad** [comment]
Wow you're on a role, thanks!
