### ISSUE TITLE
Option to Bundle Up Alts

### ISSUE THREAD

**Issue by danielhickman** [afollestad/polar-dashboard#59]
The option to bundle `chrome, chrome alt, and chrome alt 2` or (option again) `chrome` and `chrome alt and chrome alt 2`

For option one, all chrome related icons could have an icon in the corner like shown in Google Photos. 
![screenshot_2016-02-12-22-39-52-02](https://cloud.githubusercontent.com/assets/5341898/13026370/d7893afe-d1d9-11e5-8fb0-aa0ac6dddbef.jpeg)

Chrome's alts (only) could be bundled in one square with four spots for icons with the last spot being +how many icons aren't shown in the small spots. 

I hope this is a good feature to you guys and that I made at least some sense.

**Comment by TWellington** [comment]
It seems like it would get messy really quick with icons with multiple
variants, and that it'd be more work for the user to see the alts. But I
see both sides. @afollestad, what do you think?

**Comment by afollestad** [comment]
It'll definitely be quite a bit of work, and it'll slow down the loading process since it would need to detect alts. It's up to you though. @TWellington

**Comment by TWellington** [comment]
@afollestad if it slows down the loading process, then it's not worth it. I'm gonna go ahead and close this.
