### ISSUE TITLE
applyInsetsToViewMargin error

### ISSUE THREAD

**Issue by Bones28** [afollestad/polar-dashboard#60]
Used PUT, it worked but gave me this error:
cannot resolve method'applyInsetsToViewMargin(android.support.design.widget.FloatingActionButton)'
on line 38 of HomeFragment.java.

**Comment by Bones28** [comment]
as it's in the home section it's not an issue for me so i deleted that chunk of code. But for other users, it may be an issue :)

**Comment by afollestad** [comment]
This would've belonged better on PUT's issue tracker ;) this won't happen with 1.0.7 of PUT which I just uploaded: https://github.com/afollestad/polar-dashboard-upgrade-tool/releases/tag/1.0.7
