### ISSUE TITLE
NavDrawer cannot be accessed in the Icons page nor the Request page

### ISSUE THREAD

**Issue by PrattiDev** [afollestad/polar-dashboard#62]
Trying to pull it will result in scrolling up or down, or simply won't do anything at all.

**Comment by afollestad** [comment]
I'm able to do it just fine:

![affix_20160215_233317](https://cloud.githubusercontent.com/assets/1820165/13068022/8fcc1186-d43c-11e5-8898-e9d318de2e81.png)

**Comment by TWellington** [comment]
It works in every implementation I've seen so far. Closing the issue.
