### ISSUE TITLE
Status bar becomes opaque when exiting the wallpaper view.

### ISSUE THREAD

**Issue by PrattiDev** [afollestad/polar-dashboard#72]
*Only affects NavDrawer mode*

If you tap on a wallpaper and exit the full screen view, the status 
bar will become opaque/solid and wont respect the transparency effect once the navigation drawer is pulled.

**Comment by afollestad** [comment]
Not 100% sure what you mean. I'm assuming your setting `windowTranslucentStatus` to true in your theme?

---

I did that in the sample (in nav drawer mode), and it's retained just fine.

**Comment by afollestad** [comment]
Nevermind, I see what you mean.

It gets applied to the `Window` rather than the `DrawerLayout`.
