### ISSUE TITLE
The ability to select icons from other apps via Polar

### ISSUE THREAD

**Issue by ryanmkelly** [afollestad/polar-dashboard#73]
In my previous dash and in other icon packs, users were able to pull icons out via 3rd party apps such as Kustom and Zooper, this is missing and I'd love to see it be added.

**Comment by TWellington** [comment]
My rule from the very beginning on this has been that we can try to
implement this as long as the PNGs aren't exposed to the user.

**Comment by afollestad** [comment]
@ryanmkelly so basically you mean being able to select icons via Polar from another app?

**Comment by ryanmkelly** [comment]
@afollestad Pretty much, here is a screenshot from Kustom where you can choose. 
![2016-03-02 18 47 23](https://cloud.githubusercontent.com/assets/5175919/13471198/74a22ae0-e0a7-11e5-9927-2aa9e033eaad.png)

**Comment by afollestad** [comment]
@ryanmkelly that's helpful, thanks.

I'll have this in the next release.

**Comment by ryanmkelly** [comment]
@afollestad Awesome. Thank you.

**Comment by PDDStudio** [comment]
Just to append my thoughts here, depending on which app is chosen for this action, it might be possible that the icons get extracted and saved in the storage where they're publicly visible for any file browser.

**Comment by afollestad** [comment]
https://github.com/afollestad/polar-dashboard/releases/tag/1.3.2
