### ISSUE TITLE
Icons won't apply to Go Launcher via app. 

### ISSUE THREAD

**Issue by ryanmkelly** [afollestad/polar-dashboard#77]
If you apply the icons to Go Launcher inside Polar, they won't apply. They will apply however via the Go Launcher settings.

**Comment by afollestad** [comment]
I'll check on this when I'm home from work, thanks

**Comment by afollestad** [comment]
Here's the problem:

![capture](https://cloud.githubusercontent.com/assets/1820165/13545344/0f11de48-e24e-11e5-89e8-db8c37ec4262.JPG)

**Comment by afollestad** [comment]
It appears it's an issue of Go Launcher not handling incorrect drawables very well.

If you upgrade to the latest Polar code, your icon pack will tell you if you have incorrect drawables:

![screener_20160304 22-10-51](https://cloud.githubusercontent.com/assets/1820165/13545566/300235dc-e256-11e5-9c14-b6c855270449.png)
