### ISSUE TITLE
Crash on start-up. DrawableXMLParser. 

### ISSUE THREAD

**Issue by ryanmkelly** [afollestad/polar-dashboard#79]
I'm getting this crash when I start the app up on the latest source. (A fresh copy, haven't upgraded the older versions yet). 

```Gradle
03-05 18:10:48.972  28227-28247/? E/AndroidRuntime﹕ FATAL EXCEPTION: Thread-34389
    Process: com.sixtyfourthirtytwo.redux, PID: 28227
    java.lang.NullPointerException: Attempt to invoke virtual method 'void com.sixtyfourthirtytwo.redux.util.DrawableXmlParser$Category.addItem(com.sixtyfourthirtytwo.redux.util.DrawableXmlParser$Icon)' on a null object reference
            at com.sixtyfourthirtytwo.redux.util.DrawableXmlParser.parse(DrawableXmlParser.java:158)
            at com.sixtyfourthirtytwo.redux.fragments.IconsFragment$4.run(IconsFragment.java:227)
            at java.lang.Thread.run(Thread.java:818)
```

I'm assuming it's to do with broken/missing bits inside the app filter? Just want to check. 

If so, would there be any way around it? I use the same filter for my different packs, but they all have a different amount of icons in.

**Comment by afollestad** [comment]
Just a future FYI, logs format better if you use GitHub's syntax highlighting feature 😉

**Comment by afollestad** [comment]
It turns out the problem here occurs when an `<item/>` comes before a `<category/>` in your appfilter. I've fixed this problem now.
