### ISSUE TITLE
[Suggestion] Go Launcher apply frag popup. 

### ISSUE THREAD

**Issue by ryanmkelly** [afollestad/polar-dashboard#80]
Due to Go Launcher being a terrible launcher, and having the masking issue. What could be cool is to have a pop-up when pressing Go inside Polar to say something like.

"If the icons do not apply once you click continue, please open Go Settings, Press Icon and then select the icon pack. If you see un-themed icons looking distorted, please disable 'Show Icon Base' in the same menu.

**Comment by afollestad** [comment]
Good idea
