### ISSUE TITLE
Does not apply custom icons on Nova Settings (Folder background)

### ISSUE THREAD

**Issue by VictorRodriguezVR** [afollestad/polar-dashboard#85]
When I choose an icon from Polar to choose a custom folder background the icon is not applied.

![screenshot mar 7 2016 1-21-42 pm](https://cloud.githubusercontent.com/assets/7275945/13569523/c7081f50-e468-11e5-837b-58754e644a48.png)

**Comment by afollestad** [comment]
I'm not able to reproduce any problems with this.

![screener_20160307 13-02-48](https://cloud.githubusercontent.com/assets/1820165/13579816/f3bc7090-e464-11e5-81fa-0fa69b887794.png)

@TWellington?
