### ISSUE TITLE
'No Apps' message shows, but still filters unthemed apps correctly?

### ISSUE THREAD

**Issue by Jamz442** [afollestad/polar-dashboard#86]
It shows the 'No Apps' message, but it still filters the unthemed apps. Added the logcat message when that happens, but not sure if it will be helpful.
![screenshot_2016-03-09-15-03-51](https://cloud.githubusercontent.com/assets/8374134/13639452/b56e9c82-e608-11e5-906b-94d06d23da03.png)
<img width="1376" alt="screenshot 2016-03-09 15 09 35" src="https://cloud.githubusercontent.com/assets/8374134/13639516/0419a494-e609-11e5-9a51-b146bef028cd.png">

**Comment by ryanmkelly** [comment]
Same issue here. I think it's an app filter issue, but the same file was working fine before the 1.3.+ updates.

I edited the 'No Apps' text to show a message to the user about them being temporarily removed so I can push the other dash improvements.

**Comment by Jamz442** [comment]
Just tried a fresh copy of Polar, does not recreate the issue. However, when I loaded in my appfilter, then 'No Apps' shows, but proceeds to load just the unthemed apps. So, my question is, what in my appfilter could be causing the problem?

**Comment by ryanmkelly** [comment]
Had a little play around, managed to get it to show all the apps installed on the device, rather then filtering them. 

The app/whatever isn't scanning every line in the app filter, it's stopping with about 1000 lines to go, when I removed up to the point where it stopped scanning, it showed all the apps installed and stopped scanning a litter further up the filter.

I hope that made sense.

**Comment by afollestad** [comment]
@Jamz442 gave me a copy of his appfilter that I'll try to test with today. 

Could you send me your appfilter too, @ryanmkelly?

**Comment by ryanmkelly** [comment]
@afollestad here you go: https://dl.dropboxusercontent.com/u/610860/appfilter.xml

**Comment by afollestad** [comment]
Thanks!

I'll fix this tonight when I'm home from work.

**Comment by afollestad** [comment]
So for me, the empty text shows for less than a second before all the apps are displayed. It's not quite a bug.

**Comment by afollestad** [comment]
Code I just pushed should help, though.

**Comment by ryanmkelly** [comment]
Unfortunately, I'm still getting the exact same issue.
