### ISSUE TITLE
Ability to make a Zooper Dashboard.

### ISSUE THREAD

**Issue by Beasto** [afollestad/polar-dashboard#88]
More a feature then an issue. I'm making a widget pack and want to just have widgets and walls in it. No icons, no request feature, or anything like that. Is this done easily or oddly difficult?

**Comment by ryanmkelly** [comment]
You could probably just hide the tabs you don't want from the app as a work around.

**Comment by afollestad** [comment]
Well you can remove pretty much every tab from the customization file, all the comments tell you what you can do with the values. E.g. removing the wallpaper URL disables the wallpaper tab, removing the request email disables the requests tab.

**Comment by Beasto** [comment]
> Well you can remove pretty much every tab from the customization file, all the comments tell you what you can do with the values. E.g. removing the wallpaper URL disables the wallpaper tab, removing the request email disables the requests tab.

Thanks for the quick reply Aidan. I'm going to try this, it's going to be odd though. I may or may not be releasing a 235 widget pack.

**Comment by TWellington** [comment]
We also decided that we wouldn't be making any other dashboards out of
Polar some time ago. If a developer wants to tweak Polar to their needs,
they can feel free to do so (it is open source, after all). I know someone
is already using Polar as a CM Theme dashboard.

**Comment by Beasto** [comment]
> We also decided that we wouldn't be making any other dashboards out of
Polar some time ago. If a developer wants to tweak Polar to their needs,
they can feel free to do so (it is open source, after all). I know someone
is already using Polar as a CM Theme dashboard.

That's pretty cool. I think I might actually add icons in now. This is going to be crazy weird. I'm going to hangouts you.

**Comment by PDDStudio** [comment]
@Beasto There are already Zooper-Dashboards (open source, ofc) out there, which might be easier to use than disabling all the stuff of polar. But this is up to you ;)

**Comment by Beasto** [comment]
Yeah, I know. I was working with UZD by Sky and Florian. But it doesn't support bitmaps o_0

On Wed, Mar 16, 2016 at 5:04 AM, Patrick J < notifications@github.com [notifications@github.com] > wrote:
@Beasto [https://github.com/Beasto] There are already Zooper-Dashboards (open source, ofc) out there, which might be easier to use than disabling all the stuff of polar. But this is up to you ;)
