### ISSUE TITLE
Use Polar Exclusively for Wallpapers

### ISSUE THREAD

**Issue by ItsXyzzy** [afollestad/polar-dashboard#89]
Hey I wanted to use Polar for exclusively Cload Based Wallpapers but I am not sure where to go to delete the Icons out of the menu, also how can I change the icons for each of the tabs

Thank you

**Comment by afollestad** [comment]
All of the tabs can be removed from `dev_customization.xml` and `dev_zooper.xml`, except for the Icons tab and About tab. 

This dashboard is designed specifically for icons, so you'll have to remove the Icons tab yourself. The about tab can not be removed.
