### ISSUE TITLE
Icon requests should let you send multiple requests if the limit hasn't been reached yet

### ISSUE THREAD

**Issue by Beasto** [afollestad/polar-dashboard#90]
Even with a maxCount set to 10 I can still only request one icon before my limit starts.

In other words, it doesn't let you send multiple requests until the limit is reached.

**Comment by TWellington** [comment]
What do you mean?

**Comment by danielhickman** [comment]
It sounds like he wants to be able to send two requests with five icons to get to get to the limit of ten.

**Comment by Beasto** [comment]
Sorry Tom, I didn't get the notification. Yes. The issue is that, even after one request with 1 icon, the timer will start and you can't request anymore. And yes that's any maxcount greater than 0.

**Comment by TWellington** [comment]
Gotcha

**Comment by afollestad** [comment]
@Beasto @TWellington this feature is done and live in the code, let me know how it works. (I tested it and it seems to work well)
