### ISSUE TITLE
Quick Apply Sometime Appears the Size of the Other Launchers

### ISSUE THREAD

**Issue by danielhickman** [afollestad/polar-dashboard#97]
I can't reproduce this issue, but thought it would be nice to report.

Polar 1.5

![screenshot_2016-04-01-05-57-38](https://cloud.githubusercontent.com/assets/5341898/14207608/072a7414-f7d0-11e5-8ae6-6370c6fb08cc.png)

**Comment by afollestad** [comment]
I haven't experienced this issue at all, not even once.

@TWellington ?

**Comment by TWellington** [comment]
I've never seen it boo :/
