### ISSUE TITLE
Package Name Issue and Sync Issue 

### ISSUE THREAD

**Issue by uidhinc** [afollestad/polar-dashboard#98]
![screenshot_20160408-122229](https://cloud.githubusercontent.com/assets/18343840/14376233/67ff69ec-fd85-11e5-9480-2b91c850e593.png)

I have followed your Github Tutorial.And ended here.Now I want that process name to change .
it still shows your package name.How do I have my own package name for every theme ?

**Comment by afollestad** [comment]
That's the path to the code files in `src`
